### ISSUE TITLE
Wald F test in glmmTMB

### ISSUE THREAD

**Issue by AlineMuyle** [glmmTMB/glmmTMB#1080]
Hi,
I am running a model on a proportion with betabinomial(link = "logit") family, there is overdisperssion in my model.
In this paper Bolker et al (2008) Generalized linear mixed models: a practical guide for ecology and evolution
they suggest to use Wald F or Wald t or QAIC when there is overdisperssion. 
However I can't find a way to compute Wald F in glmmTMB, the only function I found glmmTMB:::Anova.glmmTMB(model, test.statistic = "F") returns an error "F tests currently unavailable".
Thanks in advance for your help!

**Comment by AlineMuyle** [comment]
Thank you so much for your prompt response!
Yes I have one random factor, here is my model and its summary:
> model_CHH_meth = glmmTMB(cbind(number_methylated_reads, number_UNmethylated_reads) ~ strata * sex + (1|GeneName), family=betabinomial(link = "logit"), data = XYpairs_promoters_CG[context == 'CHH'])

> summary(model_CHH_meth)

	 Family: betabinomial  ( logit )
	Formula:          cbind(number_methylated_reads, number_UNmethylated_reads) ~ strata *  
	    sex + (1 | GeneName)
	Data: XYpairs_promoters_CG[context == "CHH"]
	
	     AIC      BIC   logLik deviance df.resid 
	  5468.4   5524.1  -2723.2   5446.4     1157 
	
	Random effects:
	
	Conditional model:
	 Groups   Name        Variance Std.Dev.
	 GeneName (Intercept) 1.16     1.077   
	Number of obs: 1168, groups:  GeneName, 381
	
	Dispersion parameter for betabinomial family (): 2.59 
	
	Conditional model:
	                          Estimate Std. Error z value Pr(>|z|)    
	(Intercept)                -2.1521     0.1699 -12.664  < 2e-16 ***
	strataStratum 2            -0.2516     0.2981  -0.844  0.39865    
	strataStratum 3             0.6446     0.2041   3.158  0.00159 ** 
	sexX male                  -0.1530     0.2374  -0.644  0.51927    
	sexY male                   1.1169     0.1786   6.254    4e-10 ***
	strataStratum 2:sexX male   0.5549     0.3727   1.489  0.13657    
	strataStratum 3:sexX male   0.2272     0.2754   0.825  0.40929    
	strataStratum 2:sexY male  -0.4879     0.3271  -1.492  0.13582    
	strataStratum 3:sexY male  -0.6669     0.2225  -2.997  0.00272 ** 
	---
	Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Do you think it is ok to use the p-values Pr(>|z|) provided for the fixed effects even though there is significant overdispersion of the data? Are these p-values for Wald Z test?

> testDispersion(model_CHH_meth)

	DHARMa nonparametric dispersion test via sd of residuals fitted vs. simulated

	data:  simulationOutput
	dispersion = 0.78447, p-value = 0.008
	alternative hypothesis: two.sided

**Comment by bbolker** [comment]
There are a few different issues here.

* it's critically important to allow for overdispersion if you're using a GLM family that uses a fixed dispersion parameter (the main ones here are Poisson and binomial).
* However, you've already accounted for this major issue by using beta-binomial rather than binomial.
* F (or t) tests handle a different aspect of uncertainty, a finite-size correction. With 381 genes, your 'denominator degrees of freedom' (ddf) in the F or t test are likely to be so large that these will barely differ from the chi-squared or Z test. A rule of thumb is that the ddf are usually not *smaller* than the minimum number of levels of random effects, and that ddf > 50 means that the results of the Z and t tests will be very similar, unless you're trying to distinguish among very small p-values.
* I don't really understand why the DHARMa overdispersion test is giving you a significant values ... maybe you have overdispersion, or outliers, in your data?

Please send follow-up questions to [Cross Validated](https://stats.stackexchange.com), or possibly the DHARMa issues list, as these are really modeling/statistical questions, or the `r-sig-mixed-models` mailing list (although this isn't really a mixed-model-specific question either) ... see https://github.com/glmmTMB/glmmTMB/blob/master/README.md#where-to-ask-questions

**Comment by AlineMuyle** [comment]
Thank you so much for this rule of thumb on the dof and the choice between Z and t test, this is good to know!
Actually the issue was not overdispersion but underdispersion, sorry my mistake:

> testDispersion(model_CHH_meth_XYpairs, alternative = "greater") # Greater corresponds to testing only for overdispersion.

	DHARMa nonparametric dispersion test via sd of residuals fitted vs. simulated
	
	data:  simulationOutput
	dispersion = 0.78447, p-value = 0.996
	alternative hypothesis: greater

> testDispersion(model_CHH_meth_XYpairs, alternative = "less") # less corresponds to testing only for underdispersion.

	DHARMa nonparametric dispersion test via sd of residuals fitted vs. simulated
	
	data:  simulationOutput
	dispersion = 0.78447, p-value = 0.004
	alternative hypothesis: less

However the AIC test tells me the beta-binomial is by very far significantly better than the binomial distribution, so I am thinking of sticking with the beta-binomial even if it brings underdisperssion issue.

Thanks again for your help, I will move to Cross Validated for follow-ups.
Best wishes
