### ISSUE TITLE
Prediction

### ISSUE THREAD

**Issue by Hejiewang** [glmmTMB/glmmTMB#1126]
I want to evaluate the exposure response relationship between PM2.5 concentration and anemia. I used `crossreduce` packaged with `dlnm` for dimensionality reduction, but I encountered an error. My code is here: 

```
library(tidyverse)
binary_China_data <- read.xlsx("China_anemia_analysis.xlsx")
categorical_vars_China <- c("SEX","NA13","NA14","nA4b","AA6","BG9","group_age","pro","binary_anemia") 
binary_China_data[categorical_vars_China] <- lapply(binary_China_data[categorical_vars_China], factor)
pollutant<-"nature_PM2.5_inexposure"
China_data <- binary_China_data %>%
  filter(
    .data[[pollutant]] > quantile(.data[[pollutant]], 0.01, na.rm = TRUE) &
      .data[[pollutant]] < quantile(.data[[pollutant]], 0.99, na.rm = TRUE)
  )
cb.pm<-crossbasis(China_data[[pollutant]],
                  argvar=list(fun="ns",df=3)) 
fit1 <- glmmTMB(binary_anemia~cb.pm+SEX+NA13+NA14+nA4b+AA6+BG9+group_age+(1|pro), data=China_data, family=binomial(link="logit"))
pred <- crossreduce(cb.pm,fit1,cen=1,by=0.1)
```
#my warning is in crossreduce function： ”Error in vcov[indvcov, indvcov, drop = FALSE] :   incorrect number of dimensions“
I want to know how to fix this question. Are there other ways to assess the exposure response relationship between PM2.5 and anemia, if a cross-base approach is not feasible. Thanks.

**Comment by bbolker** [comment]
You haven't given us a reproducible example. My guess would be that `crossreduce` is running into trouble because the `glmmTMB` package returns a covariance matrix that has a different structure.  I would try

```
pred <- crossreduce(basis = cb.pm, fit = fit1, cen=1, by=0.1, vcov = vcov(fit1)$cond)
```

and see if that works.  If it doesn't work, please follow up on [Stack Overflow](https://stackoverflow.com) or `r-sig-mixed-models@r-project.org` -- see https://github.com/glmmTMB/glmmTMB/blob/master/README.md#where-to-ask-questions

**Comment by bbolker** [comment]
OK.  You should probably consider opening an issue on the [dnlm GH repo](https://github.com/gasparrini/dlnm/issues) to see if your changes should be incorporated in the package ...
