### ISSUE TITLE
Issues with random effects: Error in fitTMB(TMBStruc) : negative log-likelihood is NaN at starting parameter values

### ISSUE THREAD

**Issue by rafreuse** [glmmTMB/glmmTMB#1127]
I do not succeed in running a beta regression with a random effect in R. When I add one or two random effects to the formula, I keep receiving "Error in fitTMB(TMBStruc) : negative log-likelihood is NaN at starting parameter values".

The two random effects are "Municipality" (37 clusters that contain one up to more or less 15 observations) and "Party" (10 clusters that contain four up to more or less 50 observations). The total number of observations are 331.

This is my code:
# Fit an empty beta regression model with random effects
beta_empty_ag <- glmmTMB(
  relative_attention_trans ~ 1 + (1 | Party_name_clustered) + (1 | Municipality_x),
  family = beta_family(),
  data = data_lmm_migration
)

Can someone help me out? Thank you very much!

**Comment by bbolker** [comment]
Can you see whether an even simpler example, e.g.

```r
library(glmmTMB)
data("sleepstudy", package = "lme4")
glmmTMB(~ Days + (1 | Subject), data = sleepstudy)
```

gives you the same error? I strongly suspect that this is an installation issue, e.g. see [this issue](https://github.com/glmmTMB/glmmTMB/issues/1118) (which was eventually closed due to lack of response).

See also [this Stack Overflow question](https://stackoverflow.com/questions/77533611/error-in-glmmtmb-after-matrix-update-negative-log-likelihood-is-nan-at-starting) (read the comments, not the answer ...)

If this is the problem, then re-installing `Matrix` and `TMB` and `glmmTMB` (ideally from source, in that order, in a clean R session) should resolve the problem.

**Comment by rafreuse** [comment]
Indeed, it appeared to be an installation issue. I made use of an older R version in RStudio in which an earlier version of the Matrix package was installed. Now, everything works thanks to the updates.

Thank you very much, Ben!
