### ISSUE TITLE
variance structures broken

### ISSUE THREAD

**Issue by mebrooks** [glmmTMB/glmmTMB#129]
I'm testing the latest version to see what all has changed and many of the tests are breaking. Some of them are simple things like changing `fixef(fm2)` to `fixef(fm2)$cond`. However, all the tests of the variance structures now fail
```
fm2us   <- glmmTMB(Reaction ~ Days +   us(Days| Subject), sleepstudy)
fm2cs   <- glmmTMB(Reaction ~ Days +   cs(Days| Subject), sleepstudy)
fm2diag <- glmmTMB(Reaction ~ Days + diag(Days| Subject), sleepstudy)
```
They all produce the same error
```
Error in substitute((TERM), TERM = term[[2]]) : 
  unused argument (TERM = term[[2]])
```

Koen and I are looking into it, but this is a reminder that we should run `make test` before merging into the master branch.

**Comment by koenvanbenthem** [comment]
The problem is in the function noSpecials_

**Comment by koenvanbenthem** [comment]
Proposed fix:
substitute((TERM),list(TERM=term[[2]]))
instead of:
substitute((TERM), TERM = term[[2]])

Can this be agreed upon?

**Comment by koenvanbenthem** [comment]
Seems to work again -- will merge it in again.

**Comment by mebrooks** [comment]
ba58d52abee780b638e78c397a701a3f282f4824

**Comment by bbolker** [comment]
this is a little weird, because I thought I was testing as I went along.  I would blame it on @mmaechler, but some of these look unrelated to what he's been doing.  Version/platform differences??  (As long as it all works in the end, I'm fine with it.  I was just worried that we might be having branch/git confusion ...)
