### ISSUE TITLE
make test only runs example(glmmTMB)

### ISSUE THREAD

**Issue by mebrooks** [glmmTMB/glmmTMB#146]
It seems that currently, `make test` only runs a few examples. Is there another way (implemented) to call the full range of tests? Or should the Makefile be updated?

**Comment by bbolker** [comment]
you can always `R CMD build ...; R CMD check ...` ...

**Comment by mebrooks** [comment]
Doing `R CMD build glmmTMB; R CMD check glmmTMB` in the terminal gives error
```
* checking for file ‘glmmTMB/DESCRIPTION’ ... ERROR
Required fields missing or empty:
  ‘Author’ ‘Maintainer’
```
It's strange because the description has me specified with the role `"cre"`.

In an R console, the command `devtools::check()` gives the error
```
Updating glmmTMB documentation
Loading glmmTMB
Error in library.dynam("glmmTMB", pkg, lib) : 
  shared object ‘glmmTMB.so’ not found
Calls: <Anonymous> ... load_all -> run_pkg_hook -> <Anonymous> -> library.dynam
Execution halted
```
Are these errors specific to my computer, or do these work for you? I could also check with Koen when  we're in the office tomorrow.

**Comment by bbolker** [comment]
I'm not sure about the `devtools::check()` issue (at least I haven't tried yet), but I was insufficiently clear about what `R CMD check ...` should be -- you should do `R CMD check glmmTMB_0.0.1.tar.gz` (or `glmmTMB_x.y.z.tar.gz` where `x.y.z` is the package version you just built).  The explanation is that the `DESCRIPTION` file gets modified/augmented when building the package.  There are lots of discussions on the R help list about weird stuff that can happen when checking the package directory rather than the package tarball; checking the package tarball is definitely the recommended approach.

**Comment by mmaechler** [comment]
@mebrooks :  The official sequence is

    R CMD build glmmTMB
    R CMD check glmmTMB_<..>.tar.gz

"They" emphasize running the tarball through check.  
Really that is only necessary when use  the 'Authors@R: ....'  syntax in DESCRIPTION, because the build step adds the  Authors: .... ' part  but only in the tarball not in your source directory.

Martin

**Comment by bbolker** [comment]
Here's the current setup:

- `make check`: builds package & runs (full, but not --as-cran)  `R CMD check`
- `make test`: run tests (only), via `devtools::test()`
- `make ex-test`: runs just `example(glmmTMB)`
- `make quick-check`: runs `quick-install` (compile *without* optimization) & run `ex-test`

checking on Travis now.
