### ISSUE TITLE
handle evaluation environments better

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#158]
At present if you try to do something fancy with splines and predicting the result from a model matrix, you'll get the wrong answer ...

**Comment by mebrooks** [comment]
I came across this issue while looking for causes of an error in my other package. I suspect that it was fixed in `glmmTMB` after I copied the source code; so it hasn't been fixed in my other package yet. If this bug still existed in glmmTMB, would predictions from the following code look terrible in the range of observed points (not just the extrapolated points)?

```
library(glmmTMB)
library(ggplot2)
x=10:20
dat = data.frame(x=x, y=1+0.5*x-0.001*x^2+rnorm(length(x)))
m0 = glmmTMB(y~bs(x, df=3), dat)
newdata = data.frame(x=1:30)
newdata$y = predict(m0, newdata)
ggplot(dat, aes(x, y))+geom_point()+geom_line(data=newdata)
```
If that's it, then we can close this issue. 

By any chance, can you point me to a place in the `glmmTMB` code that would give me a clue how to fix this? I checked all my uses of `eval` and `eval.parent` in `predict` and they seem the same.

**Comment by mebrooks** [comment]
I think this might have been fixed in #403 and #422. I'm investigating.

**Comment by bbolker** [comment]
Sorry to not to have responded sooner, but it looks like you found it ... ?

**Comment by mebrooks** [comment]
I confirm that #403 and #422 fixed this.
