### ISSUE TITLE
summary of gamma distributed model doesn't report residual variance

### ISSUE THREAD

**Issue by mebrooks** [glmmTMB/glmmTMB#163]
Some users might want the dispersion or residual variance for models with `family=Gamma("log")`. `glm` reports dispersion. `glmer` reports residual variance. 

See #57 for code to reproduce.

**Comment by bbolker** [comment]
I actually think `glmer`'s reporting of residual variance is a mistake ...

**Comment by mmaechler** [comment]
and we should call it 'dispersion' as `glm` (and still report it), no?

**Comment by bbolker** [comment]
#168 is closely related.

I'm running out of time/this is a slightly deeper rabbit hole than I expected, so I'm just going to state some questions and observations.

- we need to double-check, and document, how we're parameterizing the dispersion/scale. For Gaussian models the `betad` parameter is `log(sigma^2)` (so `sigma==exp(0.5*betad)`), for other models we are just reporting `sigma` as `exp(betad)`.  We should check Gamma, beta, nbinom families so we know -- and document! -- what's going on in each case.
- at present, "dispersion" in `glm` is the inverse of what we are reporting as `sigma` for Gamma families. (Are we fitting the shape parameter, and dispersion is 1/shape?  That would make sense, since CV=1/sqrt(shape) ...)  We could implement these details in `sigma.glmmTMB` -- that would be a reasonably central location (and Gamma and gaussian would be the only special cases). **OR** ... we could change the Gaussian and Gamma parameterizations internally so that "sigma" was *always* exp(betad) ...

The only common exponential-family members with free scale parameters are Gaussian and Gamma (and the latter is the only one commonly fitted in `glm`).  `MASS::glm.nb` does the annoying thing of reporting  e.g.
```
(Dispersion parameter for Negative Binomial(47.7889) family taken to be 1)
```

I think it might be OK to *not* report dispersion for family=gaussian or sigma==1?

**Comment by bbolker** [comment]
I think this is resolved by https://github.com/glmmTMB/glmmTMB/pull/170 (feel free to comment/reopen if not)
