### ISSUE TITLE
problem with dispformula when updating from Poisson to nbinom

### ISSUE THREAD

**Issue by mebrooks** [glmmTMB/glmmTMB#194]
Families without dispersion end up with `dispformula= ~0` to mean that the dispersion is not an estimated variable and the dispersion model should not be used in predictions and summary output. For Gaussian models, we're allowing  `dispformula= ~0` to mean that the dispersion is not an estimated variable and it should be fixed at 0 (i.e. all the variance should go into the RE). This is a [new feature](https://github.com/glmmTMB/glmmTMB/commit/56fc6659e83f7901335e9c856d566f1b2402454f).  Poisson models end up with  `dispformula= ~0` which causes an error if we update to a negative binomial `~0 dispersion not implemented for 'nbinom2' family`. To avoid this, anytime we update from a Possion to a negative binomial, we need to change the `dispformula ` as in 
```
update(poisson_model, family="nbinom1", dispformula= ~1)
```
If no one objects I can make these changes in the tests and vignettes.

**Comment by bbolker** [comment]
Hmm.  I think we should think about this a bit.  For models with intrinsically fixed dispersion (binomial, Poisson), shouldn't we just be ignoring the dispformula entirely?  I don't want to add complexity in the wrong place ...  Another possibility (although it might have its own issues) would be to give `dispformula` a `NULL` default that converted to `~0` or `~1` appropriately.

**Comment by mebrooks** [comment]
I think an alternative solution could be to change what is stored in `call` [here](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/R/glmmTMB.R#L413). In `call` and in the resulting `glmmTMB` model object, we can save the `dispformula` that really was specified. That one could be `NULL`.  We would replace `NULL` for an other one we send to  `mkTMBStruc`. I'm not sure which version would be needed for `modelInfo` [here](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/R/glmmTMB.R#L527). Does that sound ok?

**Comment by kaskr** [comment]
Have no strong opinions but just want to mention this alternative *simple* option:

Use the `mapArg` inside `mkTMBStruct` to fix `betad` to an arbitrary value (e.g. zero) for all non-dispersion families.

This way we can set `dispersionformula = ~1` as default (to signify 'use if possible') and never again have to think about `~0` vs `~1` bookkeeping.

**Comment by bbolker** [comment]
Yes, I was hoping for something simple.  The problem that you are encountering is partly (completely?) driven by my fix [here](https://github.com/glmmTMB/glmmTMB/commit/617a16425aa7c5518ddaa36374054bdc42ff378c#diff-97ff024177e8f3aa12528855cf13b42cR413), which I think in general is not a bad idea but which is only really necessary because someone decided [here](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/R/methods.R#L319) that we needed to add an extra space between `~` and the rest of the formula when printing (introduced [here](https://github.com/glmmTMB/glmmTMB/commit/d33354a91b55146130b4937238ea0be0c51d727d#diff-78cfb91921fd8124fcde7d0dae54be1c)). I thought about changing

```
cat.f("Dispersion:      ",rep(' ',pass+2),'~ ', deparse(cc[[2]]), sep='')
```

to

```
cat.f("Dispersion:      ",rep(' ',pass), deparse(cc), sep='')
```

but wasn't sure so I left it alone ...

**Comment by mebrooks** [comment]
I think @kaskr's suggestion sounds good, but will also require making changes to the `trivialDisp` function that checks if the dispersion is trivial or not. It's used to control some of the output.

**Comment by bbolker** [comment]
OK.  Main thing is to add as little complexity as possible/have to deal with these questions in as few places as possible in the code ...

**Comment by mebrooks** [comment]
I'm working on a solution. @kaskr and I talked a bit and decided that in the fitted model object, it makes sense to have `call` contain the `dispformula` that was originally specified, while `modelInfo` can contain a different version that is altered for fitting. I'm currently testing it and making the output (`print.summary`) look better.

**Comment by mebrooks** [comment]
Here's how I have it working now...
This poisson model ignores the `dispformula`while fitting, except to give a warning, but it keeps it as part of the call.
```
fit_zipoisson <- glmmTMB(NCalls~(FT+ArrivalTime)*SexParent+
                                     (1|Nest),
                                     data=Owls,
                                     ziformula=~1,
                                     dispformula=~ BroodSize,
                                     family=poisson)
```
So that this nbinom model uses `dispformula=~ BroodSize`
```
fit_zinbinom <- update(fit_zipoisson,family=nbinom2)
```
Does that seem reasonable?

**Comment by bbolker** [comment]
Could you push it to your branch so we can see how it works in more detail?

**Comment by mebrooks** [comment]
Coming right up. I forgot to mention the obvious part that updating from poisson to nbinom works because the altered `dispformula` isn't saved in the possion call
```
> fit_zipoisson2 <- glmmTMB(NCalls~(FT+ArrivalTime)*SexParent+
                                     (1|Nest),
                                     data=Owls,
                                     ziformula=~1,
                                     family=poisson)
> fit_zipoisson2$call
glmmTMB(formula = NCalls ~ (FT + ArrivalTime) * SexParent + (1 | 
    Nest), data = Owls, family = poisson, ziformula = ~1)
> fit_zinbinom2 <- update(fit_zipoisson2,family=nbinom2)
> fit_zinbinom2$call
glmmTMB(formula = NCalls ~ (FT + ArrivalTime) * SexParent + (1 | 
    Nest), data = Owls, family = nbinom2, ziformula = ~1)
```

**Comment by mebrooks** [comment]
You might want to look at `glmmTMB.R` line 420 and tell me if it's going to cause problems. The previous version (below) returned an empty list when `dispformula=NULL`. What was the purpose of the complexity?
```
call$dispformula <- as.formula(dispformula, env=parent.frame())
```

**Comment by bbolker** [comment]
The complexity is related to [this comment above](https://github.com/glmmTMB/glmmTMB/issues/194#issuecomment-263315680); @koenvanbenthem set things up (for cosmetic reasons, I think) so that we add a space between the tilde and the rest of the formula for the ZI and dispersion formulas. This broke when I assigned the ZI formula to an object *and* didn't force evaluation of the `ziformula` element of the call (e.g. `ziform <- ~1+x; glmmTMB(..., ziformula=ziform)`). An analogous situation could happen with the dispersion formula.  I think (1) we could go ahead and let go of the extra space between the tilde and the rest of the formula; (2) in `.prt.call.glmmTMB`, we test `!is.null(cc <- call$dispformula))`; this could easily be `length(cc <- call$dispformula)>0`, which would work equally well for `list()` and `NULL` ...

**Comment by bbolker** [comment]
If we don't evaluate the `call` object then dispersion formulas specified as objects won't get expanded when printed. I would prefer that they *did* get expanded, if this doesn't break anything, but I could live without it. Right now the dispersion and zero-inflation formulas are getting printed even if they're trivial, as in this snippet from `test-methods.R`:

```
Formula:          round(Reaction) ~ Days + (Days | Subject)
Zero inflation:                 ~0
Dispersion:                     ~1
```

I would prefer that these *not* be printed - perhaps we should test for `trivialDisp()` and (if we have such a function? `trivialZI()` rather than the length of the call slots?  (That's probably more robust anyway.)

**Comment by mmaechler** [comment]
I'm coming late (and am a bit feverish..)  but if I read the above ('an hour ago') correctly, it does make a difference if we have a space somewhere in the formula or not.
This should *never* be the case;  maybe we *still* have code dealing with strings instead of language objects ????

**Comment by mmaechler** [comment]
... and of course I agree with @bbolker (43 min ago)  that in cases of no zero inflation that line should not be printed.    For the  'Dispersion' line it should probably depend on the model family: If the model family always has "internal" dispersion=1  it should not be printed either.
If however, you'd have a gamma family and set yourself (or by default) the dispersion to '1' but you can have (and often have) non-trivial dispersion for the family,  it may be nicer to print the `Dispersion :   ~1`
even in that case.

**Comment by mmaechler** [comment]
To the  `deparse(cc)`  above:  Yes, that's preferable to a manual `"~ "`   addition.
Actually I would even use  `format(cc)`  [the same here]... because that is what "one uses" for formatting R objects for output.

**Comment by mebrooks** [comment]
Ok. I see that my solution isn't compatible with objects for formulas. So we shouldn't use that one. We could use @kaskr's solution and write a better version of `trivialDisp` and use it more consistently in the print methods. Does that sound like a complete solution?

**Comment by bbolker** [comment]
Yes please.
