### ISSUE TITLE
CRAN error

### ISSUE THREAD

**Issue by kaskr** [glmmTMB/glmmTMB#221]
It seems we have an error on one of the CRAN test machines (solaris-sparc):
https://cran.r-project.org/web/checks/check_results_glmmTMB.html
There aren't many hints about what went wrong:
`Running the tests in ‘tests/AAAtest-all.R’ failed.`
I suspect it could have to do with tolerances used by our tests?

*update*: I overlooked `[90m/90m]` indicating that the tests were stopped after 90 minutes. None of then actually failed.

**Comment by bbolker** [comment]
This may be difficult to diagnose/fix.  You may indeed be right about tolerances.  Brian Ripley is notoriously grumpy about testing frameworks other than the base-R approach (independent tests as files in the `tests/` directory --  grepping my mailbox for "Ripley obfuscation", here are a couple of excerpts from messages I've received about other packages (`lme4`, `phylobase`) in the past:

> [lme4] Here we go again, tests with tolerances plucked out of thin air which fail:
> https://www.r-project.org/nosvn/R.check/r-patched-solaris-sparc/lme4-00check.html
> Your test-obfuscation suite obfuscates the tolerance used and does not return the objects when it fails, so closer inspection is precluded.

> [phylobase] Following JMC's changes to @<- in R-devel, these are failing their tests.  Since you use obfuscation suites in your tests, we'll leave you to find your own errors:

We could try searching the `r-pkg-devel`/`r-devel` archives for help, and/or asking for help (on the former; I'm suggesting the `r-devel` archives as well because `r-pkg-devel` is relatively new)

**Comment by kaskr** [comment]
I think one will need access to a solaris-sparc machine in order to sort this out.
Meanwhile, we may have to simply disable the tests for this platform.
