### ISSUE TITLE
Memory allocation fail in function 'MakeADGradObject'

### ISSUE THREAD

**Issue by iqbaleric** [glmmTMB/glmmTMB#241]
Hi experts, 

I am hitting this error for my data while running random slope zero-inflated negative binomial model. Increasing memory does not help. Tried with 126 GB memory node but still getting same error. Any suggestion is highly appreciated.

Thanks

**Comment by bbolker** [comment]
We need more information, please.  At a minimum, what are the dimensions of your problem (how many observations, how many predictors (i.e. what will the total length of your fixed-effects coefficient vector(s) be?), how many random effects, how many levels of each?  Can you successfully fit a subset of your data?  Does it work if you simplify in some way (e.g. leave out the zero-inflation)?  Is there any chance we can have a reproducible example?

**Comment by iqbaleric** [comment]
Number of observations - 25083
I am using 5 predictors as fixed-effect. For the random slope part defined as (A|B) where A has 624 levels and B has 597 levels. I tried with subset of data with this random slope part but never got success. Tried to remove zero-inflation part but didn't help.

**Comment by bbolker** [comment]
I think your problem is with your `(A|B)` term.  This will attempt to fit a 624*624 (!) variance-covariance matrix describing the variation in the effects of `A` among levels of `B`, which will lead to an attempt to estimate 195,000 top-level parameters (624*625/2). I'm not sure why you're having a *memory* problem with it, but I wouldn't expect it to be statistically practical in any case unless you had millions of observations (and then probably not computationally practical).  What are you trying to achieve with this model? Consider `(1|A)+(1|B)`, or `(1|A)+(1|B)+(1|A:B)` if you have multiple observations per A/B combination?

**Comment by bbolker** [comment]
PS if you really wanted `(A|B)` you could use something like a compound-symmetric model ...

**Comment by bbolker** [comment]
In the absence of any more info from the OP I'm going to close it. (Willing to reopen if something else comes along.)
