### ISSUE TITLE
Incompatibility with car::Anova (chi-squared tests)

### ISSUE THREAD

**Issue by ecp52** [glmmTMB/glmmTMB#242]
I wish to use a glmmTMB model and test the significance of individual terms with a chi-squared test in car::Anova.

```
library(glmmTMB)
library(car)
 Owls <- transform(Owls,
                    Nest=reorder(Nest,NegPerChick),
                    logBroodSize=log(BroodSize),
                    NCalls=SiblingNegotiation)
m.nb<- glmmTMB(NCalls~FoodTreatment + ArrivalTime + (1|Nest),
                 data = Owls, zi=~1, family = "nbinom2")
Anova(m.nb)
```

Gives:
Error in I.p[c(subs.relatives, subs.term), , drop = FALSE] : 
  subscript out of bounds
In addition: Warning message:
In is.na(coef(mod)) :
  is.na() applied to non-(list or vector) of type 'NULL'

It would be super if there could be a way for glmmTMB to feed results to car::Anova. The fits are very speedy compared to glmmADMB, which does work with car::Anova.
Thanks!

**Comment by gudryan** [comment]
@bbolker , have you found some adjust for Anova::car?

Thank you very much!

**Comment by ziab1** [comment]
If this can be fixed, glmmTMB would be become very useful for testing fixed effects when constrained with sample sizes, or when LRT isn't appropriate to test for fixed effects.

@bbolker, is there an alternative to using Anova::car to obtain Wald chi-squared or F tests using glmmTMB? If not, can this calculation be done by hand, if it's tough to incorporate into TMB?

**Comment by bbolker** [comment]
edited code above (it was using `glmmADMB` syntax, which is *slightly* different from `glmmTMB` syntax).

This does work with the latest development branch (since 7ba86a972 / 10 July 2018, I believe); it looks like it won't have made it into the latest CRAN release (0.2.2.0, 3 July 2018), but should go in the next release (probably in a month or two); in the meantime see the bottom of the [README file](https://github.com/glmmTMB/glmmTMB/blob/master/README.md) for installation instructions for the development version ...
