### ISSUE TITLE
How to find t-statistics for overdispersion parameter in glmmTMB package (zero-inflated negative mixed effect )

### ISSUE THREAD

**Issue by zohorasultanarhd** [glmmTMB/glmmTMB#251]
I am running zero-inflated negative mixed effect model. How can I find t-statistics for overdispersion parameter to make sure that overdispersion parameter from the model is statistically significant.

**Comment by bbolker** [comment]
This might be better for `r-sig-mixed-models@r-project.org` because it's as much a statistical question as a computational one.  There are several things going on here. I realize my answer here may be a little overwhelming, but it's because there isn't a single simple answer to your question. If necessary, please follow up on `r-sig-mixed-models` rather than here ...

- do you mean "negative binomial" rather than "negative"? (I don't understand what "negative" would mean by itself)
- there are two sources of overdispersion in the model: one is the negative binomial 2 family (vs. Poisson)
- there are a variety of different ways of testing the 'significance' of terms in a model
- one possibility is to fit the various model possibilities ({Poisson, NB2} x {Zero-inf, no zero-inf}) and compare them via AIC or likelihood ratio tests
- you can look at the standard deviations and/or Wald confidence intervals of the parameters that control the amount of zero-inflation and/or the overdispersion, but there are some conceptual difficulties with this (see below)
- when you say "t statistic" (rather than e.g. "z statistic") it implies that you may be interested in finite-size corrections, which I don't know how to derive for these cases.

## fitting model variants

```
library(glmmTMB)
m1    <- glmmTMB(count~spp + (1|site), zi=~1, family=nbinom2, Salamanders)
m1P   <- update(m1,family=poisson)
m1NZ  <- update(m1,ziformula=~0)
m1PNZ <- update(m1,family=poisson,ziformula=~0)
```

## AIC comparison
```
bbmle::AICtab(m1,m1P,m1NZ,m1PNZ)
##       dAIC  df
## m1NZ    0.0 9 
## m1      2.0 10
## m1P   140.4 9 
## m1PNZ 290.7 8
```

In this case the model with NB2 but without Z-I is best (we'll see below that the estimated zero-inflation parameter is effectively equal to zero for this case)

## likelihood ratio tests

These can only be done with *nested* series of models, so we can compare, for example, (Poisson/no Z-I, NB/no Z-I, NB/Z-I):
```
anova(m1,m1NZ,m1PNZ)
##       Df    AIC    BIC  logLik deviance  Chisq Chi Df Pr(>Chisq)    
## m1PNZ  8 1992.7 2028.4 -988.33   1976.7                             
## m1NZ   9 1702.0 1742.2 -842.00   1684.0 292.66      1     <2e-16 ***
## m1    10 1704.0 1748.7 -842.00   1684.0   0.00      1          1    
```

Both LRT and AIC are *asymptotic* tests (i.e., no finite-size correction)

## standard errors

```
summary(m1)
## Overdispersion parameter for nbinom2 family (): 0.941
## ...
## Zero-inflation model:
## (Intercept)   -16.81    3562.64  -0.005    0.996
m1$sdr
##            Estimate   Std. Error
## ...
## betazi -16.80601223 3562.6438847
## betad   -0.06087906    0.1350010
```

The zero-inflation parameter is fitted on the logit scale, the dispersion
parameter is estimated on the log scale. Wald confidence intervals are approximate, and particularly terrible for extreme parameter values (such as the zero-inflation parameter in this case).

```
wald.ci <- function(m,s,trans=exp) {
    trans(m+c(-2,2)*s)
}
wald.ci(-16.8,3562,plogis)  ## 0 1
wald.ci(-0.0609,0.135,exp)  ## 0.718277 1.232568
```

The null values for these parameters are -Inf (for Z-I) and +Inf (for overdispersion), so we can't really use these confidence intervals to test easily.

**Comment by zohorasultanarhd** [comment]
Yes, this is negative binomial 2 family. I am looking for the significance score of dispersion parameter using z-statistics. I could find that using another package (pscl) for ZINB model. 
  
> summary(m2 <- zeroinfl(count~spp + mined|spp + mined, 
+                ,data=Salamanders, link = "logit", dist = "negbin", trace = F, EM = F))
Pearson residuals:
     Min       1Q   Median       3Q      Max 
-0.96949 -0.49515 -0.29905  0.03491 14.30961 

Count model coefficients (negbin with log link):
            Estimate          Std. Error  z value  Pr(>|z|)    
(Intercept) -0.20665    0.27855   -0.742    0.45815    
sppPR       -0.62551     0.44074   -1.419    0.15583    
sppDM        0.15387    0.22924    0.671    0.50208    
sppEC-A     -0.32139    0.32227   -0.997   0.31864    
sppEC-L      0.57295     0.22283    2.571   0.01013 *  
sppDES-L     0.61169    0.22050    2.774   0.00554 ** 
sppDF       -0.07679     0.23500    -0.327   0.74384    
minedno      1.05950    0.21480    4.932   8.12e-07 ***
Log(theta)   0.46333    0.21708    2.134    0.03281 *  

Zero-inflation model coefficients (binomial with logit link):
            Estimate Std. Error z value Pr(>|z|)    
(Intercept)   1.1821     0.4972   2.377   0.0174 *  
sppPR         1.5875     0.7097   2.237   0.0253 *  
sppDM        -0.8262     0.6472  -1.277   0.2017    
sppEC-A       1.0743     0.6236   1.723   0.0850 .  
sppEC-L      -0.3919     0.5756  -0.681   0.4960    
sppDES-L     -0.7145     0.5919  -1.207   0.2274    
sppDF        -1.6347     0.8931  -1.830   0.0672 .  
minedno      -2.6801     0.4491  -5.967 2.41e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 

Theta = 1.5894 
Number of iterations in BFGS optimization: 26 
Log-likelihood: -820.1 on 17 Df

So, my question is -

1. Is the dispersion parameter of glmmTMB is similar like the parameter theta in pscl package?
2. How can I find the z-statistics for dispersion parameter in glmmTMB?

I will send a separate email to r-sig-mixed-models@r-project.org. Thanks for your response.

**Comment by bbolker** [comment]
1. Yes.
2. see below, but be aware that **the Z-statistics measure the distance from zero**; in this case that tests the null hypothesis that the underlying distribution is *geometric* (log(theta)=0 means theta=1, which corresponds to a geometric distribution). This is **not** a test for significant overdispersion. If you want to test for overdispersion, the best way might be to compare the likelihood of a Poisson vs. a negative binomial model (e.g. via `anova()`), although this is generally conservative for technical reasons. (There's some discussion [here](http://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#overdispersion) as well.)

Let's compare pscl and glmmTMB.

```
library(pscl)
data("bioChemists", package = "pscl")
m1 <- zeroinfl(art ~ .|1, data = bioChemists, dist = "negbin")
coef(summary(m1))
##                Estimate Std. Error    z value     Pr(>|z|)
## Log(theta)   0.81730566 0.11994374  6.8140752 9.487209e-12

## same thing in 
library(glmmTMB)
m2 <- glmmTMB(art ~ .,
         ziformula=~1,
        data = bioChemists, family=nbinom2)
m2$sdr
##
betad    0.81730439 1.199375e-01
```

This is the same estimate as `pscl` gets.  If you want to get a p-value for the difference of this parameter from zero (but see statistical caveats above!) you can compute `2*pnorm(0.817,mean=0,sd=0.1199,lower.tail=FALSE)`.

**Comment by zohorasultanarhd** [comment]
Thanks for your reply. For the following mixed effect model I get theta (m2$sdr). Can you please clarify what it is and its corresponding estimate and standard error? 
(m2 <- glmmTMB(count~spp + mined + (1|site), 
  zi=~spp + mined, 
  family=nbinom2, Salamanders))
summary(m2TMB)
 Family: nbinom2  ( log )
Formula:          count ~ spp + mined + (1 | site)
Zero inflation:         ~spp + mined
Data: Salamanders

     AIC      BIC   logLik deviance df.resid 
  1670.3   1750.7   -817.1   1634.3      626 

Random effects:

Conditional model:
 Groups Name        Variance Std.Dev.
 site   (Intercept) 0.1443   0.3799  
Number of obs: 644, groups:  site, 23

Overdispersion parameter for nbinom2 family (): 1.51 

Conditional model:
            Estimate Std. Error z value Pr(>|z|)    
(Intercept)  -0.6104     0.4052  -1.506  0.13197    
sppPR        -0.9637     0.6436  -1.497  0.13430    
sppDM         0.1707     0.2353   0.725  0.46828    
sppEC-A      -0.3871     0.3424  -1.130  0.25836    
sppEC-L       0.4879     0.2383   2.047  0.04062 *  
sppDES-L      0.5895     0.2278   2.588  0.00965 ** 
sppDF        -0.1133     0.2439  -0.464  0.64232    
minedno       1.4294     0.3666   3.899 9.66e-05 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Zero-inflation model:
            Estimate Std. Error z value Pr(>|z|)    
(Intercept)   0.9100     0.6279   1.449    0.147    
sppPR         1.1614     1.3346   0.870    0.384    
sppDM        -0.9393     0.8005  -1.173    0.241    
sppEC-A       1.0424     0.7140   1.460    0.144    
sppEC-L      -0.5623     0.7263  -0.774    0.439    
sppDES-L     -0.8930     0.7535  -1.185    0.236    
sppDF        -2.5398     2.1817  -1.164    0.244    
minedno      -2.5630     0.6045  -4.240 2.24e-05 ***
m2TMB$sdr
sdreport(.) result
           Estimate       Std. Error
beta   -0.6103772  0.4051948
beta   -0.9637019  0.6435972
beta    0.1706834  0.2353347
beta   -0.3870563  0.3424437
beta    0.4879482  0.2383224
beta    0.5894869  0.2277577
beta   -0.1132663  0.2438714
beta    1.4293504  0.3665982
betazi  0.9100389  0.6279091
betazi  1.1614050  1.3346371
betazi -0.9393237  0.8005285
betazi  1.0424293  0.7139840
betazi -0.5623149  0.7263065
betazi -0.8929958  0.7535323
betazi -2.5398143  2.1817253
betazi -2.5630264  0.6045330
betad   0.4132043  0.2481585
theta  -0.9677762  0.4202872
Maximum gradient component: 8.535375e-05

**Comment by mebrooks** [comment]
Your output from `m2$sdr` contains the line `betad 0.4132043 0.2481585`. As the top line of the output states, this is the estimate and standard error. Related to Ben's comments, I do not know of any reason why you would test if this estimate is different from zero. 

Since the dispersion model is fit on the log scale, the actual dispersion parameter, theta, is exp(betad)=1.51 as the summary states. The descriptions for all dispersion models are in the help file `?sigma.glmmTMB`. There, it explains that for the `nbinom2` family, a larger dispersion parameter means less dispersion. If a Poisson distribution were better than `nbinom2` in this model (i.e. no overdispersion), then the estimated dispersion parameter would be very large. It is possible to test the Poisson vs `nbinom2` using likelihood based inference methods (AIC or LRT) that Ben described above.

**Comment by zohorasultanarhd** [comment]
I just need to know what is theta -0.9677762 0.4202872? (below
betad).Thanks.

**Comment by mebrooks** [comment]
That theta is used to parameterize the variance-covariance matrix of the random effects in the conditional model. In this simple case, it's the log of the standard deviation of the random effect in the conditional model. 
```
> exp(-0.9677762)^2
[1] 0.1443445
```
