### ISSUE TITLE
post-hoc test like lsmeans for multiple interaction terms 

### ISSUE THREAD

**Issue by elenarosskopf** [glmmTMB/glmmTMB#258]
Hello, 

I am really happy that the beta distribution is working fine with my response variable. 
Now, as the R square is fine and the predictions make sense, I want to know the influence within the interaction terms. 

Normally my response is between 0 and 1. 

if I do `lsmeans( model, "var1")` I have estimates of 2 or 3. Not between 0 an 1. Because my other variables are missing. Of course.

How can I include all interaction terms in lsmeans and still have a look at the within-variable differences ? 

```
m = resp  ~  a*b + c*d + e*f + (1|k) 
family= beta, link=logit.
```

**Comment by bbolker** [comment]
Can we have a reproducible example please?  Are you sure that the unexpected values are because you're leaving out interactions and not because you're getting predictions on the link scale (logit) rather than the prediction scale?  Have you looked at the lsmeans documentation on interactions(section 6 of `vignette("using-lsmeans")`) ?

**Comment by elenarosskopf** [comment]
Hello! 

Thank you for the idea about the scale. I was pretty certain, it might be enough to set type to "response" but as soon as I backtransformed the LSmeans I got my predictions on the right scale.
require(RVAideMemoire)

lsm <- lsmeans(m, ~a*b, type="response")
back.lsmeans(lsm, transform="logit")
