### ISSUE TITLE
dispersion factor in NB, Conway-Maxwell Poisson & OLRE

### ISSUE THREAD

**Issue by adriana000** [glmmTMB/glmmTMB#269]
Hi,
When I detect overdispersion in a Poisson model, I move to other distributions, like Conway-Maxwell- Poisson or Negative binomial, or fit Poisson GLMM with observation level random effects. In these cases, it make sense to calculate dispersion parameter? Because these models include some parameter related to variance... Or it could be useful to detect zero augmented distributions?
Thank you in advance

**Comment by bbolker** [comment]
Questions about statistical approaches (rather than reports of bugs or requests for features for the software) are more appropriate on `r-sig-mixed-models@r-project.org` (you should register first; you can find the info/registration page by googling).

That said, if I can rephrase your question as "is it useful to test for overdispersion in a model where the scale parameter is estimated rather than fixed to a reference value (e.g., 1 in a Poisson model)?" the answer is "no".

Follow-ups (if any) to `r-sig-mixed-models` please.

**Comment by adriana000** [comment]
Ok, I got it. Thanks!
