### ISSUE TITLE
gmlmTMB 0.1.4 under R 3.2.4?

### ISSUE THREAD

**Issue by pviton** [glmmTMB/glmmTMB#273]
Am I doing something wrong or is 0.1.4 not usable under R 3.2.4? After installing the package I tried library(glmmTMB) and got a response:

Error : object ‘sigma’ is not exported by 'namespace:stats'
In addition: Warning message:
package ‘glmmTMB’ was built under R version 3.4.2 
Error: package or namespace load failed for ‘glmmTMB’

If this version really isn't usable under R-3.2.4, perhaps this should be noted on the package's CRAN page?

**Comment by bbolker** [comment]
Hmm. The NAMESPACE file (for 0.1.4 on CRAN, and in the devel version as well) has

```
if(getRversion()>='3.3.0') importFrom(stats, sigma) else importFrom(lme4,sigma)
```

I'm *guessing* that the warning about "built under R version 3.4.2" is indicating what's actually messing you up. I don't know for certain that conditional statements in the NAMESPACE file are evaluated in the environment (i.e., R package version) in which the package is built rather than the R version when the package is loaded, but it would be conceivable.

Are you willing to try installing from source to see if that makes the problem go away? (You'll need compilation/package-building tools installed .)

**Comment by mmaechler** [comment]
Yeah that's  the case: For efficiency reasons, the NAMESPACE is nowadays read at build time, not at load time, so if you want to use such an old version of R, you need to install the package from source.

**Comment by pviton** [comment]
Good idea - installing from source. In fact I'd already installed an archive version from source and it worked; I hadn't realized that installing the current version from source might solve my problem, but it does. (You may also need to install TMB the same way).
