### ISSUE TITLE
implement offsets for zi and disp components

### ISSUE THREAD

**Issue by kaskr** [glmmTMB/glmmTMB#286]
I expected an offset in `dispformula` was just ignored. It is actually passed as a fixed effect offset (!):

```
library(glmmTMB)
x <- 1:10
y <- 1:10
struct <- glmmTMB(y~1, dispformula=~offset(x), doFit=FALSE)
struct$data.tmb$offset
```

>  [1]  1  2  3  4  5  6  7  8  9 10

Same for the `ziformula`:

```
struct <- glmmTMB(y~1, ziformula=~offset(x), doFit=FALSE)
struct$data.tmb$offset
```

>  [1]  1  2  3  4  5  6  7  8  9 10

Even more weird, when multiple offsets are given it seems like the sum of all offsets is used as offset for the fixed effects:

```
struct <- glmmTMB(y~1+offset(x^2), dispformula=~offset(x), doFit=FALSE)
struct$data.tmb$offset
```

>  [1]   2   6  12  20  30  42  56  72  90 110

I see no reason why we shouldn't allow offsets for all the formulas except - looking a the R-code - it seems surprisingly complex to handle offsets ?

Some simplifications of the offset handling could perhaps be obtained by adding the offsets as separate columns to the design matrices and then fixing the corresponding beta parameters to one using the `map` feature.

**Comment by bbolker** [comment]
We did have a `FIXME` that said to throw an error if offsets were specified in ziformula/dispformula (presumably because we knew we hadn't implemented anything to deal with them) ...

I think the reason things get weird is that we add "offset" as a column to the model frame. As long as we were careful to designate these as "offset.(cond|zi|disp)" I would think it should work ...

A lot of the complexity in offset handling comes from the fact that offsets can be passed either as separate arguments (which still have to be evaluated in the same environment as the formula) or as part of the formula.  I have a pretty strong preference for the latter (allowing two ways to do the same thing always adds complexity/fragility to the code)

**Comment by bbolker** [comment]
For the very short term, we could throw an error if the offsets are specified in zi/disp (but I know we want to add the functionality for offsets in disp so that we can do weights properly ...)

**Comment by kaskr** [comment]
It's not urgent to fix this. Just wanted to make sure we don't forget.

**Comment by bbolker** [comment]
as of 71e1f7621 we do throw an error, but leaving this open until we implement the offsets (changing title and tag)

**Comment by bbolker** [comment]
I believe this is done now ...
