### ISSUE TITLE
Extracting TMB code from glmmTMB object?

### ISSUE THREAD

**Issue by sadatnfs** [glmmTMB/glmmTMB#288]
Is it possible to extract the TMB C++ code used in a glmmTMB call? I love how I can implement my models so easily in glmmTMB, and I'd love to learn about how I'd implement various implementations of those in pure TMB like AR(1) and random effects.

Thanks!

**Comment by bbolker** [comment]
Yes and no. The C++ code is here: https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/src/glmmTMB.cpp (you can also get it if you download the source version of the package from CRAN), but there are two reasons it might not be as helpful as you think:

- rather than construct specialized TMB code for each model, glmmTMB uses a general-purpose (and hence rather complicated) source file that covers *all* the possibilities it can handle
- the source code is sometimes a little more complex, or subtle, than the code you might write yourself to handle a particular situation, in order to be more robust or more efficient (this might be OK depending on what you're looking for)

On the other hand, specifying that a set of values should be treated as random effects might be easier than you think; this just needs to be specified in `TMB::MakeADFun`, with the `randomArg` parameter.
