### ISSUE TITLE
warnings and ?crash? on betabinomial + random effect + predict()

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#289]
Nels Johnson reports that the code below crashes on his system (have requested further details). Doesn't crash for me (on Linux r-devel) with development glmmTMB or fresh install of CRAN version of glmmTMB. Can anyone else replicate?

```
library(glmmTMB)
# This works without warnings or error
m1 <- glmmTMB(cbind(count,4)~ mined ,
       family=betabinomial, data=Salamanders) 
residuals(m1)
```

 50 warnings: repeated 

>  In retape() : value out of range in 'lgamma'

```
m2 <- glmmTMB(cbind(count,4)~ mined + (1|site),
      family=betabinomial, data=Salamanders)
## crashes
residuals(m2)
```

Same warnings

**Comment by kaskr** [comment]
I can reproduce the crash. It's an out-of-bounds error which should be caught automatically by glmmTMB... 

gdb points me to

https://github.com/glmmTMB/glmmTMB/blob/71e1f762153b0c21bc79f0622fed88da61b54cc0/glmmTMB/src/glmmTMB.cpp#L626

It's crashing because `yobs` is twice the length of `mu` and `phi`.
The invalid call is from `predict.glmmTMB`:

https://github.com/glmmTMB/glmmTMB/blob/71e1f762153b0c21bc79f0622fed88da61b54cc0/glmmTMB/R/predict.R#L146

It seems we forgot to split the two columns into a `yobs` vector and a `size` vector...

**Comment by mebrooks** [comment]
I guess instead of just making sure `yobs` is numeric [here](https://github.com/glmmTMB/glmmTMB/blob/71e1f762153b0c21bc79f0622fed88da61b54cc0/glmmTMB/R/predict.R#L132), we need to handle all the cases that are handled [here](https://github.com/glmmTMB/glmmTMB/blob/71e1f762153b0c21bc79f0622fed88da61b54cc0/glmmTMB/R/glmmTMB.R#L80).

**Comment by bbolker** [comment]
This is why I'm so grumpy about the extreme flexibility allowed in specifying binomial responses. In fixing this it would be **extremely** desirable to avoid replicating code.  I think that `binomial()$initialize` handles most of these cases, but if we don't like the way it does it (by evaluating in local environment), we could copy its code into a function ...

**Comment by NelsFS** [comment]
Here's the info on my computer you requested in our correspondence:

Session info -------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 system   x86_64, mingw32             
 ui       RStudio (1.0.153)           
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Los_Angeles         
 date     2018-01-17                  

Packages -----------------------------------------------------------------------
 package   * version date       source        
 base      * 3.4.3   2017-12-06 local         
 compiler    3.4.3   2017-12-06 local         
 datasets  * 3.4.3   2017-12-06 local         
 devtools    1.13.4  2017-11-09 CRAN (R 3.4.3)
 digest      0.6.14  2018-01-14 CRAN (R 3.4.3)
 glmmTMB   * 0.2.0   2017-12-11 CRAN (R 3.4.3)
 graphics  * 3.4.3   2017-12-06 local         
 grDevices * 3.4.3   2017-12-06 local         
 grid        3.4.3   2017-12-06 local         
 lattice     0.20-35 2017-03-25 CRAN (R 3.4.3)
 lme4        1.1-15  2017-12-21 CRAN (R 3.4.3)
 MASS        7.3-48  2017-12-25 CRAN (R 3.4.3)
 Matrix      1.2-12  2017-11-20 CRAN (R 3.4.3)
 memoise     1.1.0   2017-04-21 CRAN (R 3.4.3)
 methods   * 3.4.3   2017-12-06 local         
 minqa       1.2.4   2014-10-09 CRAN (R 3.3.2)
 nlme        3.1-131 2017-02-06 CRAN (R 3.4.3)
 nloptr      1.0.4   2014-08-04 CRAN (R 3.3.2)
 Rcpp        0.12.14 2017-11-23 CRAN (R 3.4.3)
 splines     3.4.3   2017-12-06 local         
 stats     * 3.4.3   2017-12-06 local         
 TMB         1.7.12  2017-12-11 CRAN (R 3.4.3)
 tools       3.4.3   2017-12-06 local         
 utils     * 3.4.3   2017-12-06 local         
 withr       2.1.1   2017-12-19 CRAN (R 3.4.3)

**Comment by bbolker** [comment]
thanks @NelsFS . Slightly less important now that @kaskr is able to replicate and we know what the problem is.

**Comment by kaskr** [comment]
I'll probably try to fix this soon. In case someone already started please let me know.
