### ISSUE TITLE
ar1 covariance with nested random effects

### ISSUE THREAD

**Issue by aosmith16** [glmmTMB/glmmTMB#329]
Should a model with an AR1 covariance structure in the residuals work with nested random effects?  I can't decide if I'm writing the model formula incorrectly or if the AR1 covariance structure is available only when there is a single random effect.

Example dataset and code:
``` r
library(glmmTMB)

# Make data.frame with correlated residuals
    # (rho = .8)
dat = data.frame(Block = rep(letters[1:5], each = 10),
                 Stand = rep(rep( LETTERS[1:10], each = 5), 2),
                 Time = rep(1:5, times = 20),
                 blockeff = rep(rnorm(5), each = 10),
                 standeff = rep( rep(rnorm(10), each = 5), 2),
                 resid = c(t(MASS::mvrnorm(20, mu = rep(0, 5), Sigma = 1*.8^abs(outer(0:(5-1),0:(5-1),"-"))))))


dat$y = with(dat, 5 + blockeff + standeff + resid)

# Model with nested random effects
fit1 = glmmTMB(y ~ (1|Block) + (1|Stand), data = dat)

# Adding residual autocorrelation in time doesn't work
    # if "Block" in the model as random effect
dat$Time = factor(dat$Time)
fit2 = glmmTMB(y ~ (1|Block) + (1|Stand) + ar1(Time - 1|Stand), data = dat)
#> Warning in FUN(X[[i]], ...): AR1 not meaningful with intercept
#> Warning in fitTMB(TMBStruc): Model convergence problem; non-positive-
#> definite Hessian matrix. See vignette('troubleshooting')

# Attempt with nested random effects style code also fails
fit2.2 = glmmTMB(y ~ (1|Block/Stand) + ar1(Time - 1|Block/Stand), data = dat)
#> Warning in FUN(X[[i]], ...): AR1 not meaningful with intercept

#> Warning in FUN(X[[i]], ...): Model convergence problem; non-positive-
#> definite Hessian matrix. See vignette('troubleshooting')
#> Warning in fitTMB(TMBStruc): Model convergence problem; singular
#> convergence (7). See vignette('troubleshooting')

# Model converges without "Block" random effect
fit3 = glmmTMB(y ~ (1|Stand) + ar1(Time - 1|Stand), data = dat)

# Here is model fit with lme() for comparison
library(nlme)
fitnlme = lme(y ~ 1, random = ~1|Block/Stand,
              data = dat,
              correlation = corAR1() )
```

**Comment by mebrooks** [comment]
In this case, coding the model's RE with the nested style isn't necessary in `glmmTMB` because the RE levels are named well in the data (in my opinion, the notation`(1|Block/Stand)` usually leads to confusion). The problem doesn't seem to involve the nesting, but it does seem like a bug to me. There might also be a bug in the print method for `fit2`. I wanted to just see what came out in spite of the warning.
```
> fit2
Formula:          y ~ (1 | Block) + (1 | Stand) + ar1(Time - 1 | Stand)
Data: dat
     AIC      BIC   logLik df.resid 
      NA       NA       NA       80 
Random-effects (co)variances:

Conditional model:
Error in r[2, 1] : subscript out of bounds
```

**Comment by mebrooks** [comment]
@kaskr, @casperwberg, and I dug through the details of this today and there were a few things going on. Internally, glmmTMB was mixing up the order of the random effects sizes and the order of the random effect types (ar1, us). We fixed them in the branch `fix_covstruct_order`. This bug would affect many models with multiple types of random effects. It happened because `mkReTrms` which we borrow from `lme4` seems to sort the RE from biggest to smallest size, but our fix just treats `mkReTrms` as a black box and doesn't depend on it's logic.

Also, in the example data simulated above, there were two time series for each Stand, but that doesn't match the RE specification. So we came up with a new example (below) that works with the new branch. I will add it to tests soon.

```
library(glmmTMB)
set.seed(101)
nb=10
ns=nb*3
nt=100
cor=.7
dat = data.frame(Block = factor(rep(1:nb, each = ns/nb*nt)),
                 Stand = factor(rep(1:ns, each = nt)),
                 Time = rep(1:nt, times = ns),
                 blockeff = rep(rnorm(nb), each = ns/nb*nt),
                 standeff = rep(rnorm(ns), each = nt),
                 resid = c(t(MASS::mvrnorm(ns, mu = rep(0, nt), Sigma = 1*cor^abs(outer(0:(nt-1),0:(nt-1),"-"))))))


dat$y = with(dat, 5 + blockeff + standeff + resid)+rnorm(nrow(dat))
dat$Time = factor(dat$Time)
fit1 = glmmTMB(y ~ (1|Block) + (1|Stand)+ ar1(Time +0|Stand), data = dat)
fit1
```

**Comment by aosmith16** [comment]
I know you're still working on this, but by chance I had to revisit the real dataset I was working with today (counts from a blocked split plot with repeated measures through time).   I can now successfully fit a model with a residual covariance structure along with multiple random effects in the fix_covstruct_order branch. :tada:

Apologies for the dataset confusion.  I was supposed to be making a simplified example dataset and clearly forgot to take out a layer from the real study design (hence multiple time series per "Stand"). :blush:
