### ISSUE TITLE
TMB version dependency 

### ISSUE THREAD

**Issue by casperwberg** [glmmTMB/glmmTMB#331]
Currently we require that TMB is at least version 1.7.6 (both CRAN and development version).
However, a colleague of mine had troubles running glmmTMB models (CRAN version) until TMB was re-installed. The dependency should be changed to TMB version >= 1.7.13.

**Comment by bbolker** [comment]
Do you know if this was a specific version dependency or is it the ongoing issue with the Matrix package being out of sync? In other words, if one were to install TMB 1.7.6 from source with Matrix 1.2-14 (I think that's the current version) installed, would it work?  Can you be more specific about the troubles?

**Comment by mmaechler** [comment]
indeed, as @bbolker says: One gets a warning (unnecessarily nowadays almost always) if a Matrix is updated and TMB is not re-installed (typically with the *same* version).
Also from 3.4.x to 3.5.0..  many packages need same-version re-installation.  Very often users problems are caused by this rather than truly requiring new versions of dependencies.

**Comment by casperwberg** [comment]
My colleague had an older version of TMB installed (I do not know which version), and we installed the glmmTMB from CRAN and tried to fit a model. This resulted in an error from nlminb (gradient was NA and wrong length). There were no warnings. Kasper suggested re-installing TMB to see if it was caused by the binary version in glmmTMB being out of sync with TMB, and after this all worked fine.

**Comment by bbolker** [comment]
Huh. While it'd be nice to know exactly what's going on, bumping the version requirement to the current CRAN version seems harmless ...

**Comment by bbolker** [comment]
This [version bump](https://github.com/glmmTMB/glmmTMB/tree/version_bump) branch is [failing on Travis](https://travis-ci.org/glmmTMB/glmmTMB/jobs/376640089) because it can't find this file in the `example("profile.glmmTMB")`:

```
salamander_prof1 <- readRDS(system.file("example_files","salamander_prof1.rds",package="glmmTMB"))
```

It works for me locally.  Can anyone explain/figure out why it's failing/fix it?

**Comment by bbolker** [comment]
I guess if we can't figure this out we can always merge the PR and fix it afterwards if the problem persists ...
