### ISSUE TITLE
zero inflation for beta distribution model

### ISSUE THREAD

**Issue by mmniu** [glmmTMB/glmmTMB#355]
Hi, I want to fit a zero-inflated beta mixed model using glmmTMB, but just realized that when I choose beta distribution in model, I can't specify anything in ziformula option, which will always give errors as below:
"Error in nlminb(start = par, objective = fn, gradient = gr) : 
  gradient function must return a numeric vector of length 4
In addition: Warning message:
In nlminb(start = par, objective = fn, gradient = gr) :
  NA/NaN function evaluation
"
I searched online and found that this error means there is inappropriate value for the response variable, so does this mean that glmmTMB can not fit beta mixed model with zero-inflation? Could anyone confirm this? 

Thank you so much!

**Comment by bbolker** [comment]
This is an interesting one.  You definitely can't do it at present, but the error you get depends on how you specify the family.  If you use `beta_family()` (preferred):

```
dd <- data.frame(z=c(rep(0,10),rbeta(100,2,2)))
glmmTMB(z~1,ziformula=~1,data=dd,family=beta_family())
## Error in eval(family$initialize) : y values must be 0 < y < 1
```

If you instead use `list(family="beta",link="logit")` you get something like the error you reported.

Since (unlike count distributions such as Poisson/NB/binomial) zero is never a feasible value for a Beta distribution (unless the first shape parameter is *exactly* 1.0; otherwise the likelihood density is either 0 or infinite), you would want to fit this as a hurdle model in any case, i.e. fit the zeros as a complete separate category from the non-zero data (*not* treating the observed zeros as a mixture of structural and sampling zeros).  You can do this by fitting a binomial (Bernoulli) model to "==0 vs >0" and a Beta model to the >0 responses ... 

I've added a  bit more on this topic (not much more than I've said here though) on the [GLMM FAQ](https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html) ("zero inflation/continuous data").

Follow-ups to r-sig-mixed-models@r-project.org , please?

**Comment by mmniu** [comment]
Hi Ben,

Thanks for your reply. To fit hurdle model using glmmTMB, do you have any
example code? will it still have the same issue? Actually i thought using
the ziformula option is the way to fit hurdle model, but since it shows
such errors of inappropriate values, i guess i may misse some options for
hurdle model. Could you please let me know the right way to do it? thanks

**Comment by bbolker** [comment]
Can you ask on `r-sig-mixed-models@r-project.org` (or StackOverflow) please?

**Comment by mebrooks** [comment]
Update: zero-inflation should be possible now with the development version after #497
