### ISSUE TITLE
vignette speed

### ISSUE THREAD

**Issue by mebrooks** [glmmTMB/glmmTMB#364]
I thought it would be easiest to discuss this here instead of in the closed pull request discussion. 
```
                    user.self sys.self elapsed
covstruct.rmd         98.386   9.048 107.590 
glmmTMB.Rnw           20.422   0.159  20.743
mcmc.rmd               1.907   0.177   2.208
miscEx.rmd             0.460   0.007   0.468
sim.rmd                2.610   0.045   2.721
troubleshooting.rmd   34.097   0.205  34.470
```

Currently, based on the times above, @kaskr is looking into speeding up `covstruct.rmd` and I'm looking into `troubleshooting.rmd` since they're the slowest and we started them. We might also need to cut some time from `glmmTMB.Rnw`.

`troubleshooting.rmd`  contains a lot of GLMMs with nbinom2, each of which takes about 3 seconds. For the parts I wrote, I tried changing all the chunks to `eval=FALSE` and pasting in the expected error or warning message. This only shaved a few seconds off the time. So I profiled and found that the following line takes 15 seconds.
```
cc = confint(zinbm1,method="uniroot",parm=9, parm.range=c(-20,20))
```
@bbolker , since you added this section, what do you suggest?

**Comment by kaskr** [comment]
Just tried to remove vignettes one by one until travis `R CMD check` got passed the vignette build step. After that the following table appears (`r-devel`):

```
* checking examples ... OK
Examples with CPU or elapsed time > 5s
                  user system elapsed        kaskr's laptop
predict.glmmTMB 21.169  0.004  21.174        0.257
VarCorr.glmmTMB 20.264  0.004  20.270        0.207
ranef.glmmTMB   15.860  0.000  15.861        0.162
confint.glmmTMB 13.527  0.000  13.528        0.167
fixef           13.363  0.000  13.365        0.174
glmmTMB          9.518  0.004   9.522        6.411
```

These timings are insane ! Compare with the corresponding timings from my laptop. Perhaps the problem is not our vignettes and tests. It seems something in `r-devel` has caused glmmTMB to slow down orders of magnitude?

A link to the travis build is [here](https://travis-ci.org/glmmTMB/glmmTMB/builds/395731481). Note that `r-release` runs our tests in 206 seconds. `r-devel` is stopped after 10 minutes.

**Comment by bbolker** [comment]
- My general suggestion for any slow computation in a vignette (which is generally useful even if @kaskr's fix gets rid of most of our current problems) is to save all of the slow-to-build objects need for a particular vignette in `inst/vignette_data`; `load(system.file("vignette_data","my_vignette.rda",package="glmmTMB"))` at the beginning of the vignette; then fake the execution  of the chunk by including a copy of the chunk with eval=FALSE and then a copy  with echo=FALSE.   It also makes sense to include a hidden chunk with a flag (`rebuild_data`) that will rebuild all the objects and store them.

**Comment by kaskr** [comment]
There's now a new TMB on CRAN which solves the timeout problem. However, our travis setup is still broken with r-devel because the package MCMCpack won't install. I think we should in general attempt to cut down on the amount of package dependencies. It's annoying when things break all the time.

@bbolker I'll follow your instructions above when reducing the covstruct vignette build time which I think is still relevant although not as urgent now. BTW, it was not my intention to actually delete vignettes - just a remedy for testing!

**Comment by mebrooks** [comment]
So does this mean that I don't need to speed up the troubleshooting vignette? All our problems should be solved if we remove the MCMCpack dependency?

**Comment by kaskr** [comment]
@mebrooks  yes, that is correct. And the MCMCpack problem is only on travis - CRAN did not complain about it. [Here](https://github.com/glmmTMB/glmmTMB/commits/travis) you can see that we get the green flag from travis by removing MCMCpack from suggested packages.

**Comment by bbolker** [comment]
I'm of two minds about dependencies.  I agree that unnecessary or marginally useful dependencies should be gotten rid of.  (Since TMB now has an `mcmc` function built in, we should use that instead of MCMCpack.) In the "effects" branch, which I would ideally like to merge in before we release, there are a whole bunch of new "Suggests:" packages. This dependency is much weaker that Imports/Depends/LinkingTo packages, which have to be installed by anyone using the package, but it does mean that Travis will attempt to install them. I've been having a bunch of trouble with installing the emmeans package, because the CRAN version depends indirectly on rstan, which takes forever to install. It looks like I may be able to make [travis install the dev version from github](https://github.com/krlmlr/r-appveyor/issues/35), which doesn't have as many dependencies ...

**Comment by mebrooks** [comment]
I asked the CRAN organizers about the timings. They say we still have a speed problem. 

These [checks](https://cran.r-project.org/web/checks/check_results_glmmTMB.html) say they were were run today. So are they really using the new TMB?

**Comment by kaskr** [comment]
Yes, I think most of the checks are using the new version.
