### ISSUE TITLE
Some years with no observations

### ISSUE THREAD

**Issue by mcfran** [glmmTMB/glmmTMB#379]
Hi, 
I am trying to develop hurdle and zeroinflated models with glmmTMB. In my datasets, some years have no encounters as no fish were detected which create some convergence issues.
In the troubleshooting vignette it is indicated that this error occurs "when complete separation occurs in a binomial model: some categories in the model contain proportions that are either all 0 or all 1".
If I excluded the years with 0% encounter it works. Is there some alternative solutions to keep these years in my models and predictions?

Thank you,
MC

**Comment by mebrooks** [comment]
In general, complete separation can be handled by adding a Bayesian prior to the model (I don't know the details since I never needed to try it). You could add Bayesian priors by changing the cpp file in glmmTMB, but that would require knowledge of how to use TMB and hacking the code underlying glmmTMB. Before attempting that, I would check if the brms package can handle this situation since it's already Bayesian. 

This type of question is probably better for R-sig-mixed.
