### ISSUE TITLE
MCMCpack potentially off CRAN by 26 Sept

### ISSUE THREAD

**Issue by mebrooks** [glmmTMB/glmmTMB#380]
Today I received this message from CRAN.

> Please remind yourselves what §1.1.3.1 of 'Writing R Extensions' says about using packages listed in Suggests conditionally.
> 
> Packages MCMCpack, fts and ndjson do not compile under the release candidate of clang 7.0.0 which is due for release next week (and their maintainers were informed several weeks ago about the problems) and so packages which require them are also not installable.  This is reflected in the current CRAN results pages for fedora-clang, with check failures for
> 
> BayesDA IPMpack bayesImageS cld2 frontier glmmTMB harvestr hot.deck lsmeans xts
> 
> Please correct to use all the Suggests packages conditionally ASAP and before Sep 26 to safely retain the package on CRAN.  ('R Internals' §8 documents an environment variable to help you check this.)

I hope MCMCpack will be able to stay on CRAN, but we need to make a plan for what to do if tit doesn't. The only use of MCMCpack is in the mcmc vignette. The part of the [guidelines](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Suggested-packages) that is referred to in the email seems to indicate that we could use some if-statements to fix the problem.

If if-statements can't fix the problem, we could move the mcmc vignette to GitHub under the [glmmTMB account](https://github.com/glmmTMB) (a level above the package). 

Another idea is that if we're already saving all the computational results for the mcmc vignette to save time (#364) then maybe we don't need to actually load/suggest the package. 

Any thoughts on this?

**Comment by bbolker** [comment]
This should be fairly easy. The vignette only uses MCMCpack as a quick way to get a Metropolis-Hastings sampler defined.  It would/will be easy enough to define our own, e.g. adapted from Florian Hartig's simple code [here]( https://theoreticalecology.wordpress.com/2010/09/17/metropolis-hastings-mcmc-in-r/) or from `emdbook::metropSB`.  

- Hartig's code is only "Metropolis", not "Metropolis-Hastings" (i.e. it doesn't account for potential asymmetry of the candidate distribution), but that shouldn't matter since we'd be using a symmetric distribution (multivariate Normal).
- We might want to think about whether we're doing adaptation or not (i.e. scaling the size of the MVN kernel) [it doesn't look like `MCMCpack::MCMCmetrop1R`, it just allows a `tune` parameter to grow/shrink the estimated variance-covariance matrix)

**Comment by bbolker** [comment]
If it passes tests etc., [this branch](https://github.com/glmmtmb/glmmTMB/tree/no_mcmcpack) should solve the problem.  It implements its own block Metropolis sampler, and also illustrates how to use `tmbstan()` (but *doesn't* explicitly make use of `tmbstan` in the code, because I don't want to drag all of the `rstan` stuff into the dependency chain for this package ...

**Comment by strengejacke** [comment]
MCMCpack was updated on CRAN a few days ago, I think this update solves the issues.

**Comment by bbolker** [comment]
In the meantime, we don't really need `MCMCpack` any more (in general, fewer dependencies are better, as this issue has shown). If someone wants to [merge the pull request](https://github.com/glmmTMB/glmmTMB/pull/388) ... (I could re-add a mention of `MCMCpack::MCMCmetrop1R` ...)

**Comment by bbolker** [comment]
resolved by a2fb9144157a9c30a3a50ded8
