### ISSUE TITLE
problems with predict() and data-dependent bases

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#402]
```
library(glmmTMB)
data("sleepstudy",package="lme4")

g1 <- glmmTMB(Reaction~poly(Days,3), sleepstudy)
predict(g1, newdata=data.frame(Days=0))

library(splines)
g2 <- glmmTMB(Reaction~ns(Days,5), sleepstudy)
predict(g2, newdata=data.frame(Days=0))

g3 <- glmmTMB(Reaction~scale(Days), sleepstudy)
predict(g3, newdata=data.frame(Days=0))
```

**Comment by bbolker** [comment]
addressed (maybe not completely??) in 79b765515

**Comment by mdwhitby** [comment]
I'm pretty sure I installed the update (PR 403). 

It now makes predictions instead of NaN - however, a warning is produced when a random effect is added. (I am not sure if this is intended or how to interpret these)

e.g.,
`#library(devtools)
#install_github("glmmTMB/glmmTMB/glmmTMB", ref=github_pull("403"))

library(glmmTMB)
data("sleepstudy",package="lme4")


nd <- data.frame(Days=0, Subject=factor("309", levels=levels(sleepstudy$Subject)))

g1 <- glmmTMB(Reaction~(1|Subject)+poly(Days,3), data=sleepstudy)
predict(g1, newdata=nd , allow.new.levels = T)

library(splines)
g2 <- glmmTMB(Reaction~(1|Subject)+ns(Days,5), data=sleepstudy)
predict(g2, newdata=nd , allow.new.levels = T)


g3 <- glmmTMB(Reaction~(1|Subject)+scale(Days), data=sleepstudy)
predict(g3, newdata=nd, allow.new.levels = T)
`

**Comment by bbolker** [comment]
Yeah, there's definitely a problem here - fix needs to be a little deeper than I had it.  When fixing the `predvars` component of the `terms` object (if you don't know what this is, you're lucky -- see `?makepredictcall` and [here](https://developer.r-project.org/model-fitting-functions.html) for more information.  Current fix doesn't preserve the *order* of values in `predvars` (there's a mismatch with the order in the formula), which is disastrous ...

**Comment by bbolker** [comment]
I think it's fixed now (fingers-crossed-emoji).  At least, your test cases now work for me. Try again?

**Comment by mdwhitby** [comment]
Thanks for getting this bug fixed so quickly - saved me a ton of work pre/post modeling.

No errors/warnings on a zero-inflated (constant) nbinom1 with 2 random effects and 12 scaled fixed.

Results look fine/feasible until I add a new polynomial fixed effect. I am not sure if this is just my data, improper use, or a continuation of the bug. 

I'd be happy to send you my glmmTMB object if you think it would help.

**Comment by bbolker** [comment]
Hmmm. Can you be more specific about what the problems are? (Warnings, errors, NaN/Inf results, obviously bogus results, subtly wrong results?) The smaller/more reproducible the better, but if it seems like it will be a lot of trouble then go ahead and send the `glmmTMB` object ...

**Comment by bbolker** [comment]
bump.  @mdwhitby , can you give provide more details?  As this is a fairly severe bug, I'd like to make sure it's resolved ...

**Comment by bbolker** [comment]
Great, I'm going to close this for now (feel free to reopen if you have fresh evidence that there's something wrong with `glmmTMB`)

**Comment by mdwhitby** [comment]
Not sure if this is related, but I didn't want to create a new issue in case it is. When I run predict, I get the following warning for every predict row. 

## Warning in f(par, order = order, ...): value out of range in 'lgamma'

I do not get a warning when fitting the model.

**Comment by bbolker** [comment]
Thanks, @mdwhitby. I think we'd like a new issue (with a reproducible example) please...

**Comment by mdwhitby** [comment]
Brought up as Issue #411
