### ISSUE TITLE
How to set the control options for all the executions?

### ISSUE THREAD

**Issue by skanskan** [glmmTMB/glmmTMB#464]
How do you set the option 
`control = glmmTMBControl(optCtrl = list(iter.max = 300, eval.max = 400), profile = FALSE, collect = FALSE))`
for all subsequent glmmTMB runs?

I mean if you run 100 models you need to write that option every time and the code gets messy and less legible.  
I would like to tell R to do it once at the beginning of my code and use it always.

**Comment by bbolker** [comment]
There's not a built-in way to do this.  I would recommend something like
I'm a little bit confused, since those are the default values for `glmmTMBControl`. You shouldn't need to set these options, they should take effect by control.

There is no built-in way to change the defaults globally.  Here are a couple of options:

1. define your own version of  `glmmTMB` (I've included the default control values here, but obviously you can change them ...
```
my_GT <- function(..., control = glmmTMBControl(optCtrl = list(iter.max = 300, eval.max = 400), profile = FALSE, collect = FALSE)) {
     glmmTMB(..., control=control)
}
```

2. you could try the `defaults` package (although a brief experiment with changing the `glmmTMBControl` options suggests this may not work, since `glmmTMB` will still call the version of `glmmTMBControl` within the package, rather than the newly created one in the global environment.
