### ISSUE TITLE
Population level effects

### ISSUE THREAD

**Issue by nelsjohnso** [glmmTMB/glmmTMB#491]
I'm having trouble figuring out how to predict the population average (i.e., fixed effects only model) in a mixed effects model in glmmTMB. Is there a hidden argument in the predict.glmmTMB function I don't know about? Is it in the developer version?

**Comment by bbolker** [comment]
On my phone, but I believe if you set grouping variables to NA in the
prediction frame that you'll get population level predictions. I think
?predict.glmmTMB mentions this. (This question might be better for
r-sig-mixed-models@r-project.org)

**Comment by bbolker** [comment]
Did this resolve your problem? (I checked, and it does seem to be documented in the CRAN version: concrete suggestions for improving the clarity/salience of the documentation are always welcome)

**Comment by ajkroeg** [comment]
My .02 on this, since I was initially confused when I first started using glmmTMB as well.  The CRAN documentation for predict.glmmTMB() does indeed mention it, but only in the context of the not-yet-implemented re.form argument.  One could be forgiven for thinking they should set re.form=NA, rather than the group value within newdata (and yes, I know there is already example code, but those are often missed while skimming the documentation).

It might help clear things up for new users if there was a specific bullet point on this under the details section, and maybe just have a note by re.form to the effect of "To compute population-level predictions, see details and examples."

**Comment by nelsjohnso** [comment]
Yeah, I used the trick Ben recommended and it worked. Thanks, Ben. I assume
I missed it because when I scanned the help file the relevant line started
with the phrase "not yet implemented" so I scanned over. Honestly I think
this information would be better suited for the "details" section of the
help file currently until re.form is implemented.

Additionally, I personally preferred SAS's implementation of GLMMs until
the emmeans package was released, in particular the emtrends function since
SAS has no similarly simple functionality for comparing slopes. So I never
learned the lingo of the package lme4 like re.form. I learned nlme because
I found it way better than nlmixed. I think it's good the conventions of
lme4 are being maintained, but it meant that for a newer user like myself I
wasn't clued into the terminology automatically when trying to scan
documentation. And "not yet implemented" encouraged me to not think more
about it.

**Comment by bbolker** [comment]
Take a look [here](https://github.com/glmmTMB/glmmTMB/commit/c8d0e5da9342cd8a329ff164afed64b42dad208c) and [here](https://github.com/glmmTMB/glmmTMB/blob/predict_doc_fix/glmmTMB/man/predict.glmmTMB.Rd) for proposed changes (a little awkward because GitHub display doesn't do line wrapping ...)

**Comment by ajkroeg** [comment]
I think that'll help clear things up.

**Comment by nelsjohnso** [comment]
This looks good.

Though, I noticed the non-parenthetical portion is not an exact copy/paste
of re.form from predict.merMod. Seems like the language between these two
packages should try to be consistent when possible.

**Comment by bbolker** [comment]
Good point. I thought the wording in `glmmTMB` was actually slightly clearer, so I changed the docs in `predict.merMod` (devel version) to match ...
