### ISSUE TITLE
Status of re.form in predict()

### ISSUE THREAD

**Issue by florianhartig** [glmmTMB/glmmTMB#505]
Hi guys, related to https://github.com/glmmTMB/glmmTMB/issues/491 - what's the status / perspective of implementing the re.form argument in predict? 

My main reasons for this is that I need fixed effects only predictions to fully support glmmTMB with DHARMa, see https://github.com/florianhartig/DHARMa/issues/16

I realize I could code a wrapper for DHARMa to set group values to NA, but that seems very hacky. As a possible solution - instead of implementing the entire re.form syntax, would it be possible to at least implement re.form ~ 0 with the next release?

**Comment by bbolker** [comment]
Agree that we should address this.  I keep getting stuck when thinking about modifying `predict.glmmTMB` because of the way it's implemented (the new data is added to the original model data to create an "augmented" data frame, which is then re-evaluated by TMB [without modifying the fitted parameters]. This makes it hard (for me, at least) to find a way to modify either the input data or the model. For example, if someone specified the model `y ~ Year + (1|factor(Year))` (a reasonable thing to do to specify a linear trend by year plus year-to-year variation), you couldn't set `Year` to NA in the new data and get just the linear trend ...

I think I've found a hack, though:

```
fm1$fit$par[names(fm1$fit$par)=="theta"] <- (-100)
```

Sets all of the random-effect variance/covariance parameters to (effectively) zero (it doesn't really make sense to set the correlation parameters to -100, but setting the log(sd) parameters to -100 means that the correlations are irrelevant ...)  This works because the conditional modes are re-computed internally on the basis of the parameters in `$fit$par`:  (`oldPar <- object$fit$par;  newObj$fn(oldPar)`), and setting variances to zero means the conditional modes will be completely pooled/squashed to zero.

If implementing this way it might be important to add `on.exit(object$fit$par <- oldPar)` so we don't risk permanently modifying the fitted object ... (since `object$fit` is a regular R object, i.e. not an environment, this might not be necessary - I think copy-on-modify will kick in).

PS using `-Inf` seems to work, too, and unless it breaks something else is safer (in case the random effects happen to be parameterized on some crazy scale) ...

This hack could be done by downstream users, but it seems safer/better to implement it in TMB.

Opinions from @kaskr and others?

**Comment by florianhartig** [comment]
Thanks for your thoughts, sounds good! If you guys hesitate to implement this but think this solution is reasonably save, I'd also be happy to implement this in DHARMa only until a more permanent solution is found for glmmTMB.

**Comment by bbolker** [comment]
bump.  I might make a branch implementing this (I'm not sure we have to hack the internal parameter values, we might be able to get away with just modifying `oldPar`?  Have to look more closely.)

**Comment by bbolker** [comment]
tentative implementation at https://github.com/glmmTMB/glmmTMB/pull/511 .  Not thoroughly tested: alpha testers welcome!

**Comment by florianhartig** [comment]
This is excellent Ben, I will give it a try as soon as possible (busy for the next days!).

**Comment by bbolker** [comment]
this is merged now, I think we can close it.
