### ISSUE TITLE
non-vector-varying covariance structures

### ISSUE THREAD

**Issue by bachlaw** [glmmTMB/glmmTMB#515]
The only mechanisms like autocorrelation and exponential smoothing that I see are in terms of vector-varying / varying-slope type structures.  Is there a way to have just a varying intercept specified with a structure like this?  Sometimes there is a simple need to define a decay function over time (e.g., sequence of years or days or whatever) and having there can be substantial benefits in specifying this without requiring covariance with some other structure.  Does glmmTMB allow this option? Thanks much.

**Comment by bbolker** [comment]
Can you be slightly more specific/explain more clearly what you want?  Looking at https://cran.r-project.org/web/packages/glmmTMB/vignettes/covstruct.html , we have e.g.  `glmmTMB(y ~ ar1(times + 0 | group), data=dat0)`  `times` needs to be specified so that `glmmTMB` knows what values are associated with what times, but this is essentially an effect on the intercept.  If you have a sequence that happens to be in order with no explicit time variable, I'd suggest defining a new variable (`index` or `n` or whatever) that makes that ordering explicit.

**Comment by bbolker** [comment]
bump ...

**Comment by bachlaw** [comment]
Thanks Ben.  The idea of setting up an index is helpful and might do the trick.  Essentially, what I was visualizing was a situation where a series of measurements was taken over days or weeks, and I want to, for example, apply an exponential weighting process as those time periods get further out.  The time measurement is essentially associated with everything, more or less, but I can give the index idea some more thought.

**Comment by bbolker** [comment]
Can you clarify whether this solves your question?  Can we close this, or can you suggest something more concrete?

**Comment by bachlaw** [comment]
I think we can close for now. Thanks Ben.

Sent from my iPhone

On Oct 11, 2019, at 7:09 PM, Ben Bolker <notifications@github.com> wrote:

﻿

Can you clarify whether this solves your question? Can we close this, or can you suggest something more concrete?
