### ISSUE TITLE
Unexpected model convergence problem/error for truncated_nbinom family

### ISSUE THREAD

**Issue by lmwang9527** [glmmTMB/glmmTMB#524]
I am testing glmmTMB on my data with the truncated_nbinom1 and truncated_nbinom2 family. My dependent variable y is a continuous variable with inflated zeros and no missing or negative values ([histogram](https://raw.githubusercontent.com/cities/dropbox/master/hist_df0.1x.png)), so I believe those families would be a good fit, but I am running into unexpected warnings and errors with them, even with the simplest possible specification. I appreciate it if anybody can help shed light on what may be going on/what I may be doing wrong!

Here is a replicable sample of data/code:
```
library(glmmTMB)
df0.1x <- read.csv("https://raw.githubusercontent.com/cities/dropbox/master/df0.1x.csv")
glmm1a = glmmTMB(y ~  1,
                 ziformula = ~ 1,
                 data=df0.1x,
                 family=truncated_nbinom1() #or truncated_nbinom2()
);

# non-sensible results with
#Warning message:
#In fitTMB(TMBStruc) :
#  Model convergence problem; non-positive-definite Hessian matrix. See vignette('troubleshooting')

glmm1b = glmmTMB(y ~  (1 | group),
                 ziformula = ~ 1,
                data=df0.1x,
                family=truncated_nbinom1() #or truncated_nbinom2()
                )
#Error in (function (start, objective, gradient = NULL, hessian = NULL,  :
#  gradient function must return a numeric vector of length 5
#Calls: glmmTMB ... with.default -> eval -> eval -> do.call -> <Anonymous>
#In addition: Warning message:
#In (function (start, objective, gradient = NULL, hessian = NULL,  :
#  NA/NaN function evaluation
#Timing stopped at: 10.44 0 10.46
```
I have gone through the troubleshooting vignette. None of the suggestions seem to be relevant, because if I change the family to poisson() or nbinom1(), both models then work fine. I also tried to add an independent variable x1 in the specification, it doesn't help.

**Comment by bbolker** [comment]
The proximal problem is that there a bunch of non-integer values, and in particular non-integer values between 0 and 1, in your data set. This code demonstrates that keeping only integer values, or only integer values and non-integer values greater than 1, returns reasonably sensible answers.
```
df2 <- subset(df0.1x,y %% 1 == 0)
update(glmm1a, data=df2)
df3 <- subset(df0.1x,y > 1 | y %% 1 == 0)
update(glmm1a, data=df3)
```

All of the truncated families have something in common; there's a line here

```
if( yobs(i) < Type(1) ) tmp_loglik = -INFINITY;
```

that is used to make sure that zero observations are not counted in the conditional (nbinom/Poisson) likelihood, only in the zero-inflation component.

This problem could be fixed by using a lower threshold (I assuming that <1 rather than == 0 was used to allow for very small but non-zero values), but alternately one might argue that we should give a warning if there are non-integer values in a Poisson/nbinom/etc. model (#474).

**Comment by lmwang9527** [comment]
Thanks for the information! I guess I misunderstood what the truncated_nbinom* family is for. It seems it corresponds to hurdle_negbinomial family (in packages like [glmmAdaptive](https://drizopoulos.github.io/GLMMadaptive/articles/ZeroInflated_and_TwoPart_Models.html#two-parthurdle-negative-binomial-mixed-effects-model) and [brms](https://rdrr.io/cran/brms/man/brmsfamily.html)), and what I want is the hurdle_lognormal family. Still figuring out how to do that with glmmTMB, but I suppose the forum or the mailing list is a better venue for questions like this.

**Comment by bbolker** [comment]
Yes, exactly.  The GLMM FAQ has a [section](https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#continuous-data) on zero-inflated positive distributions.  You could try a Tweedie distribution, or make your own hurdle by fitting a Bernoulli to I(y>0) and then a model of the conditional component based on the subset with y>0 ...
