### ISSUE TITLE
question: does the order of the random effects matter?

### ISSUE THREAD

**Issue by Delvis** [glmmTMB/glmmTMB#527]
Hi. I am analyzing vertebrate consumption data per individual and month-year-tag (my random effects). Looking at summary from the model, I got the exact same results if I swap the order of the random effects.

Random effects:

Conditional model:
 Groups Name        Variance  Std.Dev. 
 Month  (Intercept) 3.579e-01 0.5982586
 ID     (Intercept) 2.419e-08 0.0001555
Number of obs: 1092, groups:  Month, 45; ID, 36

Random effects:
  
  Conditional model:
  Groups Name        Variance  Std.Dev. 
ID     (Intercept) 2.419e-08 0.0001555
Month  (Intercept) 3.579e-01 0.5982586
Number of obs: 1092, groups:  ID, 36; Month, 45

Everything else in the model, estimates, AIC, etc is exactly the same.

But when I try to plot them using sjPlot::plot_model(), they look completely different,

(1|Month) + (1|ID)

![plot of Month](http://jcoelho.com/images/1-AMonth.png)
![plot of ID](http://jcoelho.com/images/1-BID.png)

for
(1|ID) + (1|Month),
![plot of ID](http://jcoelho.com/images/2-AID.png)

![plot of Month](http://jcoelho.com/images/2-BMonth.png)

I wrote it first as (1|ID) + (1|Month) and I was stuck for ages trying to understand why the plots were so weird. Any ideas what is going on here?

**Comment by bbolker** [comment]
Nothing immediately springs to mind. In general the order of random effects *shouldn't* matter, although I would not be incredibly shocked if it made a difference in some particularly numerically unstable case. However, you've answered your own question as far as `glmmTMB` itself goes: the results are identical, at least up to the precision displayed here. Therefore, until convinced otherwise I think this is an `sjPlot` issue rather than a `glmmTMB` issue; the sjPlot issues list is [here](https://github.com/strengejacke/sjPlot/issues) ...
