### ISSUE TITLE
challenges for implementation of inverse-link transformations in tidy model output?

### ISSUE THREAD

**Issue by jmobrien** [glmmTMB/glmmTMB#553]
offering this up as I could potentially implement if people think it's useful.  Is there any reason why the `tidy.glmmTMB` method couldn't simply implement something like the `exponentiate` param used in `tidy.rlmerMod`?  

It's pretty straightforward, and it scales estimates, CI's and SE's all at once:

```
    if (exponentiate) {
      vv <- intersect(c("estimate", "conf.low", "conf.high"), 
        names(ret))
      ret <- (ret %>% mutate_at(vars(vv), ~exp(.)) %>% 
        mutate(std.error = std.error * estimate))
    } 
```

This would be a less-flexible manual approach that is not aware of the underlying link to invert, but presumably it could be converted to something more model-aware later if need be, while boosting functionality right now.  But perhaps I'm missing other things that need considering?

**Comment by bbolker** [comment]
This is a good idea but should be addressed to `broom.mixed` rather than `glmmTMB` (see `getAnywhere("tidy.glmmTMB")$where`). I thought about this before a bit with broom/broom.mixed and concluded that one generally *doesn't* want to naively apply the inverse-link function to the parameters. In particular: exponentiating log-link parameters *does* make sense (we get fold/proportional-change estimates), but inverse-linking parameters for [0,1] models usually does *not* make sense, because the inverse-link functions aren't intercept-independent. So for logit-link parameters we want to exponentiate (to get an odds ratio), not logistic-transform; for cloglog-link parameters we want to exponentiate (to get a hazard ratio), not inverse-cloglog transform.

More generally, there should be a set of tests, and/or a capabilities table, to have arguments like `exponentiate=` implemented for all the model types for which they make sense ...

**Comment by bbolker** [comment]
added in 6a34c99b4

**Comment by jmobrien** [comment]
Apologies for not coming back to this until now.  I wasn't sure where to raise this--I knew it was actually in `broom.mixed`, but ultimately related more closely to this package than to that general-purpose one.  But if that's not the practice, I'll remember that in the future.   

Otherwise, your perspective makes sense, and I agree.  Thanks for the transfer, and the updated `tidy`!
