### ISSUE TITLE
vignettes CRAN

### ISSUE THREAD

**Issue by kaskr** [glmmTMB/glmmTMB#555]
For some reason the vignettes on CRAN no longer contain figures.
For instance the [covstruct vignette](https://cran.r-project.org/web/packages/glmmTMB/vignettes/covstruct.html) used to have an illustration of re-constructed image using a spatial model.
It would be nice if these graphics could reappear in our next CRAN submission.

I get the illustrations if I build manually:

```
make glmmTMB/vignettes/covstruct.html
```

But why doesn't CRAN get the same?

**Comment by bbolker** [comment]
We have the following incantation in the vignette YAML:

```
params:
  EVAL: !r identical(Sys.getenv("NOT_CRAN"), "true")
```

This will make code chunks *not* evaluate unless the env variable `NOT_CRAN` is set. We did this because of too many issues with computationally intensive chunks in the vignettes. (I think this can be done more subtly by storing pre-computed chunks, but this global switch is easier.)

We will have to work harder to figure out how to do this in such a way that we still get the figures built properly on CRAN. Maybe worth asking a "best practices" question on `r-package-devel`?

**Comment by bbolker** [comment]
I think 8294539b resolves this; it's a minor pain and could possibly be automated further.  It essentially executes *and stores* the figures if `NOT_CRAN` is set, and uses the figures from system files whether or not `NOT_CRAN` is set.  This *should* represent a reasonable balance between reproducibility and keeping expensive calcs from being executed on CRAN.

**Comment by bbolker** [comment]
- PS1.  Don't know if this recipe needs to be applied to pictures in other vignettes?
- PS2. The relevant commit is now 790fa434d

**Comment by kaskr** [comment]
Just checked the vignettes on CRAN. Images are now included which is great.
To my surprise [my other vignette changes](https://github.com/glmmTMB/glmmTMB/commit/625811c99a2547828a95910abc91a78fe46fd766) are not present on CRAN. I can only find one explanation: Some branch other than the master was used to build the CRAN version?
No big deal. Next submission will fix this.

**Comment by mebrooks** [comment]
Yes, I submitted from the News branch. Prior to that I checked differences with the master and even tried to rebase and git said that the only differences were the ones I made.
