### ISSUE TITLE
Error in match.arg(type) : 'arg' must be of length 1

### ISSUE THREAD

**Issue by cycloxslug** [glmmTMB/glmmTMB#574]
I am receiving this error when calling "predict" on a glmmTMB model "temptime_red_ar1" --this model runs fine and throws no errors. The predict function throws this error:
"Error in match.arg(type) : 'arg' must be of length 1"

```
a_red <- predict(temptime_red_ar1, newdata = NULL, se.fit = FALSE, allow.new.levels = FALSE, type = c("link", "response", "conditional", "zprob", "zlink"), zitype = NULL, na.action = na.pass,
             debug = FALSE)
```
The code did not result in errors in a previous version (not sure which version, but the models were last successfully run on Feb 29, 2020. ) Did something change in the "predict" call in newer versions? I can't seem to get the most likely previous version (0.2.2) to install.

**Comment by bbolker** [comment]
It would be great to have a reproducible example ...

**Comment by cycloxslug** [comment]
here is the model as an rData file.
[temptime_red_ar1.zip](https://github.com/glmmTMB/glmmTMB/files/4477063/temptime_red_ar1.zip)

Update: this definitely is something in the parameter list--it will successfully run as 'predict(temptime_red_ar1)'

**Comment by bbolker** [comment]
To be honest, I would be very surprised if this worked in February 2020.  The line where the error occurs (see [here](https://github.com/glmmTMB/glmmTMB/blame/master/glmmTMB/R/predict.R#L131)) was added when the `type` argument was added, in commit 34ef0c7a1240afea4. 

With apologies for using tidyverse machinery, if I wanted to predict all four types (which is I guess what you intended?) I would do something like this:

```
library(dplyr)
library(purrr)
tvec <- c("link", "response", "conditional", "zprob", "zlink")
names(tvec) <- tvec
map_dfr(tvec, ~predict(temptime_red_ar1, type=.), .id="type")
```
This doesn't actually work because we haven't specified `newdata` and the original data aren't available in this environment:

> Error in is.data.frame(data) : object 'subfish' not found

**Comment by bbolker** [comment]
Bump ... any further thoughts?

**Comment by cycloxslug** [comment]
I'm sorry, I don't have any further thoughts (and was at the very edge of my marginal understanding already!). Since the predict function worked without any of the parameters, we were able to get what we needed from the function.
I can say that the original posted code definitely worked at one point, and no longer worked several months later. I very much appreciate your work and thank you for following up.
