### ISSUE TITLE
How to identify the right distribution and link function of the response variable on continuous scale?

### ISSUE THREAD

**Issue by hjung9** [glmmTMB/glmmTMB#576]
Hi,

 I know how to determine distribution when the response variable is a count data by picking either poisson or negative binomial. 

**I am curious how I should identify distribution of the response variable that is continuous, not a count data.** I think it should be gamma or beta distribution, but how am I supposed to know if the response variable is following the distribution, and also, how should I choose the proper link function?
Attached is the density plot of 9 response variables I am interested (none of them are proportional data and zero-values are rarely occurring).
Maybe these are all lognormal, since the probability density at zero is zero? (Ref: https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html)
But if this is the case, which link function should I use?
If this is not the case, what should be the correct distribution and link function?
Thank you.

Best regards,
H Jung

![image](https://user-images.githubusercontent.com/44118272/79533812-d6523800-8046-11ea-94ce-3a29011840fa.png)

**Comment by bbolker** [comment]
This question is more appropriate for [CrossValidated](https://stats.stackexchange.com) or `r-sig-mixed-models@r-project.org` (see https://github.com/glmmTMB/glmmTMB/blob/master/README.md#where-to-ask-questions).

Short/incomplete answer:
1. in general you should not look at the *marginal* distribution of your responses in order to choose a model (the distribution described in a GLMM is a *conditional* distribution given the predictors)
2. in general it's best to choose a response variable on qualitative or subject-area grounds rather than by testing, e.g.
     * Beta responses are appropriate for data bounded both above and below
     * Gamma or log-Normal responses are appropriate for positive distributions
     * Gaussian distributions are for unbounded distributions, or distributions that are relatively unskewed and don't approach their boundaries (e.g. even if the distribution is theoretically positive, you can use a Gaussian as long as the coefficient of variation is well below 1, i.e. the mean is far from zero)

Keeping point 1 in mind, I'd guess that you'd be OK with a simple LMM here (i.e. Gaussian reponse).  The DHARMa package is useful for model diagnosis.
