### ISSUE TITLE
Typo in family documentation

### ISSUE THREAD

**Issue by amynang** [glmmTMB/glmmTMB#595]
Hello,
I just noticed that in `?beta_family`, the mean variance relationship for beta is given as 
`V=mu*(1-mu)*phi`
`?sigma` gives `mu*(1-mu)/(1+phi)`

(v.1.0.1)

**Comment by mebrooks** [comment]
I think `sigma` has the correct version. The `glmmTMB` code has `dbeta(mu*phi, (1-mu)*phi)` and in `TMB` the formulation is `dbeta(alpha, beta)`. From Wikipedia, `var[X] = alpha*beta/ [(alpha+beta)^2(alpha+beta+1)` which works out to `(1-mu)*mu/(phi+1)`. I'm going to change it in the `huxtable_fix` branch since I'm already working on 1.0.2 there.
