### ISSUE TITLE
Offsets break glmmTMB when called via do.call

### ISSUE THREAD

**Issue by cvoeten** [glmmTMB/glmmTMB#612]
```
library(glmmTMB)
ss <- lme4::sleepstudy
off <- rnorm(nrow(ss),10,20)
glmmTMB(Reaction ~ Days,ss,offset=off)
do.call(glmmTMB,list(Reaction ~ Days,ss,offset=off))
```
The first call works completely fine, the second gives:
```
Error in vapply(attr(tt, "variables"), deparse, character(1)) : 
  values must be length 1,
 but FUN(X[[3]]) result is length 46
```
R 4.0.2 on Arch Linux.

From the traceback, it seems that the problem may be related to unsafe use of `deparse` in `fix_predvars`. Replacing `tt_vars <- vapply(attr(tt, "variables"), deparse, character(1))[-1]` with `tt_vars <- vapply(attr(tt, "variables"), function(x) as.character(list(x)), character(1))[-1]` gets it a little further, but then the next problem is `Error in getXReTrms(formula, mf, fr, contrasts = contrasts, sparse = sparseX[["cond"]]) : trouble reconstructing offset name`, at which point I gave up.

**Comment by bbolker** [comment]
Thanks, I'll take a look.  I wish that `lm` hadn't set the original convention that offsets could be specified *either* as elements of the formula *or* as separate terms; it seems to cause so much complexity and fragility ...

**Comment by bbolker** [comment]
I think this should be fixed now: if you want to try it out from the branch, `remotes::install_github("glmmTMB/glmmTMB/glmmTMB@do_call_ofset")` should install it (yes, I did spell offset with only one f ...)

**Comment by cvoeten** [comment]
That indeed fixes the original issue, but a small change brings to light a second problem:
```
library(glmmTMB)
ss <- lme4::sleepstudy
ss <- rbind(ss,ss,ss,ss,ss,ss,ss,ss,ss,ss)
off <- rnorm(nrow(ss),10,20)
glmmTMB(Reaction ~ Days,ss,offset=off) #works
do.call(glmmTMB,list(Reaction ~ Days,ss,offset=off)) #breaks
```
```
Error in terms.formula(object, data = data) : 
  variable names are limited to 10000 bytes
```
Sorry...

**Comment by bbolker** [comment]
This one is harder.  The proximal problem is that (in order to avoid downstream problems not being able to find the variable passed as an offset) we evaluate the `offset` argument before proceeding. In the case of `do.call()

relevant code bits are [here](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/R/glmmTMB.R#L650-L657) (converts offset to within-formula *when `substitute(offset)` can be found in the data or in the environment of the formula*; AFAICT this is true in the original call (without `do.call()`). When `do.call()` is used, `substitute(offset)` is no longer short.

It seems as though `substitute(offset, env=environment(formula))` **might** work ... ?

**Comment by bbolker** [comment]
I have a mildly hacky solution to this in 22daba4659a .I would **LOVE** it if someone could review what's being done with offsets.  The last set of changes were made in 9faec931a3; the use case/tests are in `tests/testthat/test-offset.R` at "LM with offset in formula - variable not in environment".

**Comment by cvoeten** [comment]
Sorry for the delay in responding, confirming fixed also for my real-world data. Thanks for your lightning-fast response speed!
