### ISSUE TITLE
Using nbinom2 with identity link

### ISSUE THREAD

**Issue by freD3k** [glmmTMB/glmmTMB#619]
Hi there,

I'm trying to run a negative binomial generalized linear mixed model with identity link and keep getting the same error: 
Error in nlminb(start = par, objective = fn, gradient = gr) : 
  gradient function must return a numeric vector of length x

Here is a simple code example that gives this error:
```
m1 <- glmmTMB(count~ mined + cs(1|site), 
              family =  nbinom2(link = "identity"), data=Salamanders)
```

However, using a different variable as random intercept does work:
```
m1 <- glmmTMB(count~ mined + cs(1|spp), 
              family =  nbinom2(link = "identity"), data=Salamanders)
```

I can't seem to figure out what the issue is with the first one and would very much appreciate some ideas on this.

Thanks a lot!

**Comment by mebrooks** [comment]
This type of model is not expected to automatically run with an identity link because that link allows parameters to go into bad regions of parameter space, i.e. a negative mean. If you really wanted to fit this type of model for a good reason, better initial parameter values could help. See documentation for the `start` argument to `glmmTMB`. Then if you have further questions, [the R-sig-mixed list would be a better place to ask](https://github.com/glmmTMB/glmmTMB#where-to-ask-questions).
