### ISSUE TITLE
Warning From Matrix package

### ISSUE THREAD

**Issue by guilhermeparreira** [glmmTMB/glmmTMB#676]
Hi there! When I fit a model in `glmmTMB` I always get the following error message:

```
library(glmmTMB)
(m1 <- glmmTMB(count ~ mined + (1|site),
               zi=~mined,
               family=poisson, data=Salamanders))
Warning messages:
1: In Matrix::sparseMatrix(dims = c(0, 0), i = integer(0), j = integer(0),  :
  'giveCsparse' has been deprecated; setting 'repr = "T"' for you
2: In Matrix::sparseMatrix(dims = c(0, 0), i = integer(0), j = integer(0),  :
  'giveCsparse' has been deprecated; setting 'repr = "T"' for you
3: In Matrix::sparseMatrix(dims = c(0, 0), i = integer(0), j = integer(0),  :
  'giveCsparse' has been deprecated; setting 'repr = "T"' for you

```

I installed `glmmTMB` after `TBM`.

My session info:
```
R 4.0.4
Ubuntu 20.04.2 LTS

TMB_1.7.18
glmmTMB_1.0.2.1
Matrix_1.3-2
```

Any suggestions?

**Comment by bbolker** [comment]
This is fixed in the development version of the package. It's harmless. You could:
- ignore it and wait for the next CRAN release (which we keep not getting around to ...)
- install the development version from GitHub: `remotes::install_github("glmmTMB/glmmTMB/glmmTMB")` or possibly `install.packages("glmmTMB", repos="https://glmmTMB.github.io/glmmTMB/repos)`

You could also downgrade your version of Matrix to the previous version, but that seems silly.
