### ISSUE TITLE
setup issue

### ISSUE THREAD

**Issue by benjaminwnelson** [glmmTMB/glmmTMB#699]
Hello, I get the following error.

> library(glmmTMB)
Warning messages:
1: In system2("/usr/bin/otool", c("-L", shQuote(DSO)), stdout = TRUE) :
  running command ''/usr/bin/otool' -L '/Library/Frameworks/R.framework/Resources/library/tcltk/libs//tcltk.so'' had status 69
2: In fun(libname, pkgname) : couldn't connect to display ":0"

**Comment by bbolker** [comment]
(1) That's a warning message, so it won't necessarily be a problem. (2) It seems to stem from trying to call `tcltk` (an external library for graphical interfaces etc.), which is used by some parts of the R ecosystem but **not** by glmmTMB at all, so this might not even be glmmTMB-related? (At first glance, it doesn't seem to be used by any of the packages that `glmmTMB` imports either.) 

Can we see the results of `sessionInfo()` from a **clean** R session (i.e., where you have loaded nothing but `glmmTMB`)?

What happens if you try `example("glmmTMB")` ?

The only hints I can find from web-searching are that you *might* try installing XQuartz if you're on MacOS (e.g. https://stackoverflow.com/questions/48755725/incompatible-library-version-rsiena ), but I'm not convinced that those are the same problem (but installing XQuartz is very unlikely to hurt anything).

**Comment by benjaminwnelson** [comment]
Thanks! Here is the result of sessionInfo()
![Screen Shot 2021-05-27 at 11 12 26 AM](https://user-images.githubusercontent.com/36683142/119851482-6c0ff600-bedc-11eb-99df-30a9b7bc1c0b.png)

**Comment by bbolker** [comment]
The errors and warnings that you're getting when running models are discussed [here](https://github.com/glmmTMB/glmmTMB/issues/615) and [here](https://stackoverflow.com/questions/67040472/warning-in-every-model-of-glmmtmb-givecsparse); please try the [installation instructions here](http://glmmtmb.github.io/glmmTMB/) to install a new version of glmmTMB. If you are running a pre-4.0 version of R that might not work.

---

(1) Whenever possible, please post error messages/R output etc. as **text** (you can put them in a code block by surrounding them with triple-backticks <code>```</code>) rather than as a screenshot.  (2)  Your `sessionInfo()` screenshot is also missing the top line about what R version you're running, which is rather important ... (3) THat doesn't look like a **clean** R session. My `sessionInfo()` from a clean session looks like this:

```
R Under development (unstable) (2021-05-21 r80352)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Pop!_OS 20.10

Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.10.so

[irrelevant 'locale' section omitted]

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] glmmTMB_1.0.2.9000

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6          codetools_0.2-18    lattice_0.20-44    
 [4] mvtnorm_1.1-1       zoo_1.8-9           MASS_7.3-54        
 [7] grid_4.2.0          xtable_1.8-4        nlme_3.1-152       
[10] coda_0.19-4         estimability_1.3    multcomp_1.4-17    
[13] minqa_1.2.4         nloptr_1.2.2.2      Matrix_1.3-3       
[16] sandwich_3.0-1      boot_1.3-28         TH.data_1.0-10     
[19] splines_4.2.0       lme4_1.1-27         TMB_1.7.20         
[22] emmeans_1.6.0       survival_3.2-11     numDeriv_2016.8-1.1
[25] compiler_4.2.0     
```

**Comment by bbolker** [comment]
Any further information/progress on this?  Otherwise, I will close it soon ...

**Comment by benjaminwnelson** [comment]
It worked once I loaded xquartz. Thank you!
