### ISSUE TITLE
Installing Package Issues

### ISSUE THREAD

**Issue by delucalab** [glmmTMB/glmmTMB#753]
In the past, I had an issue with the package installation for R 3.6 which was resolved. However, I had to update my R and am now running into issues. I'm using R 4.1.1 on a Mac. When I try to install the TMB binaries using the following command:

install.packages("TMB", repos="https://glmmTMB.github.io/glmmTMB/repos")

I get the following error:

Warning in install.packages :
package ‘TMB’ is not available for this version of R

I also tried installing the development version from github but received the matrix incompatibility error.

I then tried using the checkpoint package and it seems that the setSnapshot command has been removed from the most recent version of the package and I was unsure how to get around this?

Thanks for your help!

**Comment by bbolker** [comment]
Hmm. Not entirely sure why you need our version of `TMB` rather than the CRAN version?
While this *should* be better documented, you can look [here](https://github.com/glmmTMB/glmmTMB/tree/gh-pages/repos/bin/macosx/contrib/4.1) to see that we are currently offering `glmmTMB` binaries, but not `TMB` binaries, built on 4.1.

If the CRAN binaries for `TMB` really aren't working for you I can post the TMB binaries for this version. (It's not terribly difficult but it does take a little bit of effort which I will skip if it's not necessary.)  [Developers: the basic machinery for building binaries on r-hub is [here](https://github.com/glmmTMB/glmmTMB/blob/master/misc/mkrepos.R). It's not properly documented or automated, but the necessary bits and pieces are there if someone wants to (1) do the TMB building-and-posting stuff instead of/before me, (2) work on improving/documenting/automating this part of the infrastructure (https://github.com/glmmTMB/glmmTMB/issues/413)

**Comment by delucalab** [comment]
I think I may be confused. I tried using install.packages("glmmTMB") and got the matrix incompatibility error:

TMB was built with Matrix version 1.3.3
Current Matrix version is 1.3.4

When this happened before, it was recommended to install.packages("TMB", repos="https://glmmTMB.github.io/glmmTMB/repos"). But when I tried that I got the following error: 

Warning in install.packages :
package ‘TMB’ is not available for this version of R

I looked back and remembered that the checkpoint package worked for me last time but it seems that the newest version may not have the setSnapshot function so I was unsure how to address that to get around the issues?

**Comment by bbolker** [comment]
From the `checkpoint` [NEWS file](https://cran.r-project.org/web/packages/checkpoint/news/news.html) for version 1.0.0:

> ... `setSnapshot` renamed to `use_mran_snapshot` for consistency with other function names.

Can you see if that solves your problem?  I will update the README file.

**Comment by delucalab** [comment]
Looks to be all good to go! Thanks!
