### ISSUE TITLE
Bug: predict = "prob" returning "response" values for non-ZI models

### ISSUE THREAD

**Issue by bwiernik** [glmmTMB/glmmTMB#798]
If I run, `predict(object, type = "zprob")` and `predict(object, type = "zlink")` with a non-zero-inflated model, then the values returned are those for `predict(object, type = "response")`, rather than an error as described in the documentation.

> "zprob"
> the probability of a structural zero (gives an error for non-zero-inflated models)
> 
> "zlink"
> predicted zero-inflation probability on the scale of the logit link function

``` r
predict(glmmTMB::glmmTMB(mpg ~ log(disp), data = mtcars), type = "zprob")
#>  [1] 22.03911 22.03911 25.69183 17.59883 14.50276 18.87072 14.50276 22.84563
#>  [9] 23.22712 21.60783 21.60783 16.97880 16.97880 16.97880 11.98540 12.22473
#> [17] 12.63784 28.63310 28.99429 29.57691 24.70493 15.65564 16.07407 14.76457
#> [25] 13.52360 28.59774 24.68947 26.87398 14.73805 22.95396 16.16623 24.63555
predict(glmmTMB::glmmTMB(mpg ~ log(disp), data = mtcars), type = "zlink")
#>  [1] 22.03911 22.03911 25.69183 17.59883 14.50276 18.87072 14.50276 22.84563
#>  [9] 23.22712 21.60783 21.60783 16.97880 16.97880 16.97880 11.98540 12.22473
#> [17] 12.63784 28.63310 28.99429 29.57691 24.70493 15.65564 16.07407 14.76457
#> [25] 13.52360 28.59774 24.68947 26.87398 14.73805 22.95396 16.16623 24.63555
predict(glmmTMB::glmmTMB(mpg ~ log(disp), data = mtcars), type = "response")
#>  [1] 22.03911 22.03911 25.69183 17.59883 14.50276 18.87072 14.50276 22.84563
#>  [9] 23.22712 21.60783 21.60783 16.97880 16.97880 16.97880 11.98540 12.22473
#> [17] 12.63784 28.63310 28.99429 29.57691 24.70493 15.65564 16.07407 14.76457
#> [25] 13.52360 28.59774 24.68947 26.87398 14.73805 22.95396 16.16623 24.63555
```

I was also wondering if, rather than returning an error, it might be better to return a vector of `0` (zprob) or `-Inf` (zlink) for such models. This would make it easier, e.g., to addresss https://github.com/glmmTMB/glmmTMB/issues/797

**Comment by bwiernik** [comment]
Note that the results do not change if `fast = FALSE` is set.

**Comment by bbolker** [comment]
I'm trying to figure out the best way to implement this. One way would be to fill `etazi` (the linear predictor for the zero-inflation component) with `-Inf` in the C++ code if there is no zero-inflation, then let everything carry through (removing some "only if zero-inflation" components.  Another way would be to set up branching logic on the R side so that if there were no zero-inflation we filled in the special values (there are some edge cases, e.g. would we want `NA` values to stay as `NA` ... ??)

The former is more elegant/consistent, the latter is slightly more computationally efficient (we don't have to construct a whole vector of `-Inf` values, back-transform them to zero, etc. etc.) - in fact if we know that we have a non-ZI model and are being asked for ziprob/zilink, we can skip almost all of the prediction machinery ... just need to get the return length, names, etc. right ...

**Comment by bwiernik** [comment]
Yeah, I think checking `noZI()` on the R side and filling in the appropriate 0/-Inf values would be much faster

**Comment by bbolker** [comment]
I'm still a little bit worried about edge cases (in general writing `predict` methods drives me a bit crazy: `NA` values in original data or in new data, in fixed or random components, with or without rownames, original data or new data specified, etc etc etc) but I think the basic pieces are there?

**Comment by bwiernik** [comment]
Thanks!
