### ISSUE TITLE
Index out of bounds in binomial model

### ISSUE THREAD

**Issue by arnima-github** [glmmTMB/glmmTMB#80]
require(lme4)
require(glmmTMB)

cbpp <- transform(cbpp, prop=incidence/size, obs=factor(1:nrow(cbpp)))

glme.binom <- glmer(prop ~ period + (1|herd) + (1|obs), family=binomial, data=cbpp, weights=size)

tmb.binom <- glmmTMB(prop ~ period + (1|herd) + (1|obs), family=binomial(), data=cbpp, weights=size)

# Process R aborted (core dumped)

**Comment by bbolker** [comment]
The underlying problem is in `getReStruc()`, where the order of the random effect terms is getting mixed up.  In `lme4::mkReTrms` the order of the RE terms is permuted to decreasing order of number of levels.  Need to make sure that all of this extraction info is consistent (it's not presently -- `ZtList` and `cnms` are ordered differently????)
