### ISSUE TITLE
Need appropriate binary version of the package

### ISSUE THREAD

**Issue by lsaverbio** [glmmTMB/glmmTMB#813]
Hi my statistics advisor recommened this package but I'm having issues installing.  I tried everything through the R help page, but I still get this errror:
"Warning message:
In checkMatrixPackageVersion() : Package version inconsistency detected.
TMB was built with Matrix version 1.4.1
Current Matrix version is 1.4.0"

I tried these different methods and get the error:
install.packages("glmmTMB")
install.packages("glmmTMB",repos="https://glmmTMB.github.io/glmmTMB/repos",type="binary")
remotes::install_github("glmmTMB/glmmTMB/glmmTMB") 

My R studio is on a windows laptop, R version is 4.1.3

**Comment by bbolker** [comment]
This is a warning, not an error. Do your models run? 
Installing new versions of glmmTMB won't help, you need a new version of TMB.  Do you have development tools installed (https://cran.r-project.org/bin/windows/Rtools/rtools40.html)? Can you install them?

**Comment by kaskr** [comment]
In this case I think the easiest is to upgrade the Matrix package? (current version on CRAN is 1.4.1)

**Comment by bbolker** [comment]
Thanks. I hadn't noticed that the Matrix version was too *old* rather than too new ... `install.packages("Matrix")` should do it. I'm going to close this now, but please feel free to come back and comment if you can get things working.

For what it's worth, it's generally easiest to work with R if you keep your R version up to date (although admittedly version 4.2.0 was only released about a month ago).
