### ISSUE TITLE
Using glmmTMB for a binomial distribution for more than 2 variables

### ISSUE THREAD

**Issue by lsaverbio** [glmmTMB/glmmTMB#815]
Hi, My stats advisor has recommended that I use a binomial distribution for my data which has more than 2 variables in the formula (response variable, year, mat, block, name, rep, field).  She only knows SAS but was told that glmmTMB package could do a similar analysis as her SAS code.  I've tried running glmmTMB with the following formula but am getting a formula error, which I think because I have more than 2 variables: la_pro~name+year+mat+(1 | block)+(1 | rep).  This is the SAS code she is using with a model that is name/d as the binomial distribution.  She then is able to state that there are random variables as an intercept.  Is it possible to run the model in glmmTMB as she does in SAS?

SAS:
proc glimmix data = comb plots = residual panel method = quad(qpoints = 1);
 class year name block rep;
 model l_pro = name / d = binom solution;
 random intercept block block*rep/ subject = year;
 nloptions maxiter = 1000;
run;

**Comment by bbolker** [comment]
There's nothing obviously wrong with your formula, and glmmTMB can certainly handle any number of fixed and any number of random-effect terms.

Can you please post this question to `r-sig-mixed-models@r-project.org` (or Stack Overflow)? The issues list is intended for bugs and feature requests rather than usage advice (see https://github.com/glmmTMB/glmmTMB/blob/master/README.md#where-to-ask-questions ...) 

It would be good to add a little bit more detail in your post to the list/SO - in particular, what is the text of the error message you're getting? It might also help to have a little bit more scientific context.

I'm not very familiar with the [SAS syntax](https://documentation.sas.com/doc/en/pgmsascdc/9.4_3.4/statug/statug_glimmix_syntax24.htm) but it seems like your formula specification might be closer to

```r
l_pro ~ name +(1|year/block/rep)
``` 
? (I don't see `mat` in the SAS code at all ...?)
