### ISSUE TITLE
Lacks citation on what method used to estimate the residuals Covariance-matrix

### ISSUE THREAD

**Issue by DexterGlass** [glmmTMB/glmmTMB#852]
Lacks citation on what method used to estimate the residuals Covariance-matrix.

**Comment by bbolker** [comment]
To be honest I'm not sure what such a citation would be, or where it would go. `glmmTMB` has no capabilities for estimating structured covariance matrices, hence the covariance matrix of the residuals is **always diagonal**, with variances determined by the estimated dispersion parameter and (possibly) the mean for a given observation. (Since observed data are assumed to be measured without error, the variance of the residual is entirely determined by the variance of the predicted value.)

The canonical reference for `glmmTMB` is Brooks et al 2017, but to be fair it doesn't say much about the estimation procedure (it pretty much just says "uses maximum likelihood"). The package vignettes give a little more detail, but not much ...

Can you (1) say a little more about your use case and (2) suggest where you might think to look for such a citation/documentation?

---

Brooks, Mollie E., Kasper Kristensen, Koen J. van Benthem, Arni Magnusson, Casper W. Berg, Anders Nielsen, Hans J. Skaug, Martin Maechler, and Benjamin M. Bolker. “Modeling Zero-Inflated Count Data With GlmmTMB.” BioRxiv, May 1, 2017, 132753. https://doi.org/10.1101/132753.

**Comment by DexterGlass** [comment]
https://cran.r-project.org/web/packages/glmmTMB/vignettes/covstruct.html : The documentation on estimating the covariance-matrix of the residuals.

I think knowing how glmmTMB estimates the covariance lets us know whether it is heteroskedasticity, autocorrelation of residuals consistent,robust, or efficient estimator.

**Comment by bbolker** [comment]
These are all covariance structures on the *random effects*, not on the residuals. They are all estimated by (restricted) maximum likelihood. (`glmmTMB`'s only estimation options are ML and REML.)

We can certainly update this vignette to make that clear, and to clarify that if you do want to estimate structured residuals, the way to do it is usually by setting the residual variance to (effectively) zero with `dispformula = ~0` and then using an observation-level random  effect.  If you give an example of what you want to do we can try to help further. It might be best to ask on `r-sig-mixed-models@r-project.org` instead (see https://github.com/glmmTMB/glmmTMB/blob/master/README.md#where-to-ask-questions ).
