### ISSUE TITLE
No support for random-effects covariance specification in GLM, and no binomial GLM support

### ISSUE THREAD

**Issue by DexterGlass** [glmmTMB/glmmTMB#858]

**Comment by bbolker** [comment]
It's not at all clear what this means.  Can you give an example of what you're trying to do? `glmmTMB(..., family = "binomial")` certainly works ...

**Comment by DexterGlass** [comment]
running glmmTMB(y~diag(x),...,family=list(family="binomial",link="logit")) does not work. The diag function doesn't work on a glm.

**Comment by bbolker** [comment]
`y ~ diag(x)` is indeed incorrect syntax; `diag()` must be used around a *random effects term*, e.g. `y ~ diag(1|g)`.  (By the way, you should also be getting a warning about specifying the family as a list rather than a function).

For example, this works (although `diag()` doesn't actually do anything meaningful here because the random effect is scalar so the covariance matrix is 1x1).

```r
library(glmmTMB)
data("cbpp", package = "lme4")
glmmTMB(incidence/size ~ diag(1|herd), weights = size, family = binomial, data = cbpp)
```

**Comment by DexterGlass** [comment]
make sense.

**Comment by DexterGlass** [comment]
The vignette says "glmmTMB(y ~ ar1(times + 0 | group), data=dat0)" . I had assumed times was a covariate prior to asking you. I'm not used to models with no covariates and only random-effects.

**Comment by bbolker** [comment]
(1) If a term has a `|` in it, it's a random effect term. (2) This is an example that is constructed in order to illustrate random-effects covariance structures, that's why it's so simple. (3) As I may have hinted before, I think `r-sig-mixed-models@r-project.org` is a better venue for these kinds of questions - you should only post an issue if you're pretty sure that something is a bug or missing feature ... (if in doubt, you can ask on the mailing list first and then post an issue if it turns out to be warranted) https://github.com/glmmTMB/glmmTMB/blob/master/README.md#where-to-ask-questions
