### ISSUE TITLE
Hide updateCholesky() warnings from user

### ISSUE THREAD

**Issue by arni-magnusson** [glmmTMB/glmmTMB#87]
data(Owls, package="glmmADMB")
Owls <- transform(Owls, ArrivalTime=c(scale(ArrivalTime,scale=FALSE)),
                  NCalls=SiblingNegotiation)

tmbz <- glmmTMB(NCalls ~ FoodTreatment + ArrivalTime + (ArrivalTime|Nest) + (1|SexParent),
                ziformula = ~1 + (1|Nest) + (1|SexParent),
                data=Owls, family=poisson(link="log"))

**Comment by mmaechler** [comment]
I have not yet looked at the deep bowels of this...
but I *think* that a really fail proof way to be able to call the Matrix package code with an argument that tells is to not **send** these warnings.    Otherwise, we will "suppress all warnings in this call"  which may well be too coarse and also suppress other warnings which we *should* have seen.

**Comment by bbolker** [comment]
I no longer (7 years later!) get an updateCholesky() warning, presumably because Matrix has moved on (this is with Matrix 1.4.1, yes it's out of date) ... @mmaechler @arni-magnusson maybe take a quick look and confirm that this can be closed?

**Comment by kaskr** [comment]
These warnings were silenced long ago - closing now.
