### ISSUE TITLE
Load old fit to newer version/tryCatch to point to up2date?

### ISSUE THREAD

**Issue by bri2020** [glmmTMB/glmmTMB#874]
Dear all, 

is there an official function or strategy on how to load old fits (saved as RDdata/or Rds for example) into a newer R (and thus glmmTMB) version. I've seen this discussion, but as a newbie and or not fully privy to this vocabulary, it's hard for me to figure out your final choices you had. [here https://github.com/glmmTMB/glmmTMB/issues/651](https://github.com/glmmTMB/glmmTMB/issues/651)

1. should I update my R to the same version everywhere and run my model again?
2. can i load an old fit somehow?
- with update function
- or do you have something integrated that I haven't found yet?

My problem occurs when I want to plot the data 

```
plot_model(m11, type = "pred", terms = c("sex", "delta_age"), mdrt.values="quart",colors = "bw")
```
```
Error in optimHess(oldPar, obj$fn, obj$gr) : 
  gradient in optim evaluated to length 1 not 8
> traceback()
13: optimHess(oldPar, obj$fn, obj$gr)
12: eval(substitute(expr), data, enclos = parent.frame())
11: eval(substitute(expr), data, enclos = parent.frame())
10: with.default(object, optimHess(oldPar, obj$fn, obj$gr))
9: with(object, optimHess(oldPar, obj$fn, obj$gr))
8: predict.glmmTMB(model, newdata = data_grid, type = "link", se.fit = se, 
       re.form = ref, ...)
7: stats::predict(model, newdata = data_grid, type = "link", se.fit = se, 
       re.form = ref, ...)
6: get_predictions_glmmTMB(model, data_grid, ci.lvl, linv, type, 
       terms, value_adjustment, condition, ...)
5: select_prediction_method(model_class = model_class, model = model, 
       data_grid = data_grid, ci.lvl = ci.lvl, type = type, model_info = model_info, 
       ppd = ppd, terms = original_terms, value_adjustment = typical, 
       vcov.fun = vcov.fun, vcov.type = vcov.type, vcov.args = vcov.args, 
       condition = condition, interval = interval, ...)
4: ggpredict_helper(model = model, terms = terms, ci.lvl = ci.lvl, 
       type = type, typical = typical, ppd = ppd, condition = condition, 
       back.transform = back.transform, vcov.fun = vcov.fun, vcov.type = vcov.type, 
       vcov.args = vcov.args, interval = interval, ...)
3: ggeffects::ggpredict(model = model, terms = terms, ci.lvl = ci.lvl, 
       type = pred.type, ...)
2: plot_type_eff(type = type, model = model, terms = terms, ci.lvl = ci.lvl, 
       pred.type = pred.type, facets = grid, show.data = show.data, 
       jitter = jitter, geom.colors = colors, axis.title = axis.title, 
       title = title, legend.title = legend.title, axis.lim = axis.lim, 
       case = case, show.legend = show.legend, dot.size = dot.size, 
       line.size = line.size, ...)
1: plot_model(m11, 
       type = "pred", terms = c("sex", "delta_age"), mdrt.values = "quart", 
       colors = "bw")

```

Would you need to see my model or saving?
Problems occur between R/4.0.0 (model run on a cluster as Rscript) and R/4.2.0 (RstudioServer load fit to visualise).

Many thanks,
Britta Meyer

**Comment by bbolker** [comment]
Try `m11 <- up2date(m11)` and see how it goes?

**Comment by bri2020** [comment]
Thanks a lot! Oh dear, now I also found it in the current manual. I have somehow overlooked the function or equated / confused with update() for models. Works perfectly - great. A huge thank you and sorry for not being able to read/search properly. Best regards,
Britta

**Comment by bbolker** [comment]
We could try to categorize the places where an error was likely to occur from reloading an old version and use `tryCatch()` to produce a custom error message directing the user toward `up2date` ...

**Comment by bri2020** [comment]
> We could try to categorize the places where an error was likely to occur from reloading an old version and use `tryCatch()` to produce a custom error message directing the user toward `up2date` ...

Yes that would be great! Thanks again, if I find a place were to add more details in the documentation, I let you know.

**Comment by BenediktGehr** [comment]
Der all, I'm sorry to come with this issue given the long history of this post but trying to go through the answers and comments I'm having still issues with my old version glmmTMB model objects (several objects that run for 1-1.5h each). I'm trying to work with glmmTMB models I ran in 2021 ( I'm not sure which glmmTMB and TMB versions) and get the usual error a s stated above. When I tried to fix with the recommended 'up2date()' function I received an error message (which unfortunately I didn't save and can't remember what it said). So I started installing older Versions of glmmTMB and TMB and some dependencies like R.oo and R.methodsS3 because I'm getting the error: Error in registerFinalizer(Fun, DLL) :  could not find function "registerFinalizer". I'm stuck now for a long time with this and didn't manage to solve this irrespective of the versions I tried. Any help would be most apreciated. Thank you very much and best, Ben

**Comment by bbolker** [comment]
@BenediktGehr I'm sorry you're having trouble, but really the most useful way forward would probably be to restore the most recent version of glmmTMB, try loading your old model, and post the error here.  (`glmmTMB` doesn't use `R.oo` or `R.methodsS3`; these *might* be recursive dependencies of some of the "Suggests:" packages ...)

How big are your stored objects?  If we can't figure anything out from the errors we might ask you to send us a file so we can try to see what's going on.

**Comment by BenediktGehr** [comment]
Dear Ben
Thank you very much for your fast reply! I reinstalled the most recent versions of glmmTMB (1.1.7) and TMB (1.9.5) now and reproduced the original error (apologies, should have done this before posting the first time). So, this is what I get with my current object:
>> class(old_glmmTMB_model_object)
“glmmTMB”<<

>> test<-up2date(old_glmmTMB_model_object)
Error in TMB::MakeADFun(data, parameters, map = map, random = random,  :
 A map factor length must equal parameter length <<<

The error dealing with the object came as an example when using confint():

>> cc<-confint(old_glmmTMB_model_object, method = “Wald”, parm = “beta”)
Error in .Call("MakeDoubleFunObject", data, parameters, reportenv, PACKAGE = DLL) :
  Incorrect number of arguments (3), expecting 4 for 'MakeDoubleFunObject' <<

Does this already help to figure out what the issue is? The objects are quite large unfortunately, ~200MB for the RData file.

Let me know, if I should try to send you something, to help understand. I appreciate the help!



Von: Ben Bolker ***@***.***>
Gesendet: Donnerstag, 20. Juli 2023 15:00
An: glmmTMB/glmmTMB ***@***.***>
Cc: Benedikt Gehr ***@***.***>; Mention ***@***.***>
Betreff: Re: [glmmTMB/glmmTMB] Load old fit to newer version/tryCatch to point to up2date? (Issue #874)


@BenediktGehr<https://github.com/BenediktGehr> I'm sorry you're having trouble, but really the most useful way forward would probably be to restore the most recent version of glmmTMB, try loading your old model, and post the error here. (glmmTMB doesn't use R.oo or R.methodsS3; these might be recursive dependencies of some of the "Suggests:" packages ...)

How big are your stored objects? If we can't figure anything out from the errors we might ask you to send us a file so we can try to see what's going on.

**Comment by bbolker** [comment]
`vcov()`, `fixef()`, `ranef()` work because they are pulling information out of the stored R object; they don't need to go back and re-run the underlying TMB code.

Did you by any chance have an explicit `map` statement in your original model fit? In particular, the two-stage process suggested by Muff et al. 2020?

What are `old_glmmTMB_model_object$obj$env$map` and `old_glmmTMB_model_object$obj$parameters` ?

**Comment by BenediktGehr** [comment]
Yes of course, I hope this is ok like this, $b is very long with dput()

glmm.TMB.old$obj$env$map
list(theta = structure(c(NA, 1L, 2L, 3L, 4L, 5L, 6L, 7L, 8L, 
9L, 10L, 11L, 12L, 13L, 14L, 15L, 16L, 17L), .Label = c("1", 
"2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", 
"14", "15", "16", "17"), class = "factor"))
########

glmm.TMB.old$obj$env$parameters
$beta
 [1] 0 0 0 0 0 0 0 0 0 0 0 0

$betazi
numeric(0)

$b
   [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  [51] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [101] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [151] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [201] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [251] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [301] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [351] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [401] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [451] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [501] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [551] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [601] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [651] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [701] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [751] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [801] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [851] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [901] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [951] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [ reached getOption("max.print") -- omitted 270286 entries ]

$bzi
numeric(0)

$betad
numeric(0)

$theta
 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 
attr(,"shape")
 [1] 6.907755 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
[12] 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
attr(,"map")
 [1] -1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16
attr(,"map")attr(,"levels")
 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12" "13" "14" "15" "16" "17"
attr(,"nlevels")
[1] 17

$thetazi
numeric(0)

$thetaf
numeric(0)

attr(,"check.passed")
[1] TRUE

**Comment by bbolker** [comment]
- `length(glmm.TMB.old$obj$env$map)` is 18
- `length(glmm.TMB.old$obj$env$parameters$theta)` is 17

Can you try

```r
glmm.TMB.old$obj$env$map = list(theta = factor(c(NA, 1:16))
```

and see if that fixes things?

**Comment by BenediktGehr** [comment]
If I do this the R session is aborted every time I run up2date(glmm.TMB.old):

> glmm.TMB.old$obj$env$map
$theta
 [1] <NA> 1    2    3    4    5    6    7    8    9    10   11   12   13   14   15   16   17  
Levels: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17

> glmm.TMB.old$obj$env$map = list(theta = factor(c(NA, 1:16)))
> glmm.TMB.old$obj$env$map
$theta
 [1] <NA> 1    2    3    4    5    6    7    8    9    10   11   12   13   14   15   16  
Levels: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16

up2date(glmm.TMB.old) ## this runs for a few seconds and the the R session is aborted. Does this make any sense? Thanks very much for your help!

**Comment by bbolker** [comment]
I'm trying to figure out what the length of `theta`/`map` *should* be. in `(0 + a | id_anim)` (or the corresponding term for your real model), what is `a`? I would assume it must be  a factor: how many levels does it have?

**Comment by BenediktGehr** [comment]
In this example it has 18 levels (this is the most complex model): 
> glmm.TMB.random_d$call # this is my glmmTMB old object
glmmTMB(formula = use ~ -1 + open_end + open_end_hunting + +open_end_winter + 
    open_end_spring + alternate + open_end_sex + open_end_sex_hunting + 
    open_end_predators + open_end_hunting_predators + open_end_hfi + 
    open_end_ndvi + log_step_scale + (1 | locID) + (0 + open_end | 
    study_name/id_anim) + (0 + alternate | study_name/id_anim) + 
    (0 + open_end_winter | study_name/id_anim) + (0 + open_end_spring | 
    study_name/id_anim) + (0 + open_end_hunting | study_name/id_anim) + 
    (0 + open_end_predators | id_anim) + (0 + open_end_hunting_predators | 
    study_name/id_anim) + (0 + open_end_hfi | study_name/id_anim) + 
    (0 + open_end_ndvi | study_name/id_anim), data = dat_d, family = poisson, 
    REML = FALSE, start = list(theta = c(log(1000), 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)), map = list(theta = factor(c(NA, 
        1:17))), ziformula = ~0, dispformula = ~1)

**Comment by bbolker** [comment]
I'm willing to give it another try, although it will take me a little while to get my head around it again.  Is there any chance you could put one of the files somewhere I can retrieve it (share via Dropbox or Google Drive or ... ?)  That would definitely be the most efficient way for me to dig in and figure out what's going on ...

**Comment by BenediktGehr** [comment]
Many thanks for getting back to me and apologies again for asking so bluntly. If you’d find some time I’d very much appreciate it, but understand that your time is limited of course.

Of course, it’s absolutely no problem to share some model files – see below. Do you also need the input data? I’d be more than happy to also share the input data, but they are not all mine, so not sure if I’d have to ask the co-authors first. But if it would help, I can also send you a sample of the input data from my study site. Just let me know, whatever helps best to get to the bottom of this. Let me know if the dropbox link works. Otherwise, I can try some other means.

https://www.dropbox.com/scl/fi/d7sroi1t4lly14s8bcazc/day_model_full_activesteps_id_anim_woAlternate_NoSpring.RData?rlkey=rvwpf90j1qclb5j5f0km7ty7x&dl=0

Many thanks and best
Ben

Von: Ben Bolker ***@***.***>
Gesendet: 30 July 2024 15:54
An: glmmTMB/glmmTMB ***@***.***>
Cc: Benedikt Gehr ***@***.***>; Mention ***@***.***>
Betreff: Re: [glmmTMB/glmmTMB] Load old fit to newer version/tryCatch to point to up2date? (Issue #874)


I'm willing to give it another try, although it will take me a little while to get my head around it again. Is there any chance you could put one of the files somewhere I can retrieve it (share via Dropbox or Google Drive or ... ?) That would definitely be the most efficient way for me to dig in and figure out what's going on ...

**Comment by BenediktGehr** [comment]
Here I send you a link to my study site data – it’s a subset but should work well. Let me know if it doesn’t work.

https://www.dropbox.com/scl/fi/ypn4ezcu42wyac262gljt/day_data_subset_activesteps_id_anim_woAlternate_NoSpring_Bernese.RData?rlkey=iw7qhev2ksdczk5b6yxxcoazm&dl=0

Many thanks for your support, it is most appreciated!

Von: Ben Bolker ***@***.***>
Gesendet: 30 July 2024 15:54
An: glmmTMB/glmmTMB ***@***.***>
Cc: Benedikt Gehr ***@***.***>; Mention ***@***.***>
Betreff: Re: [glmmTMB/glmmTMB] Load old fit to newer version/tryCatch to point to up2date? (Issue #874)


I'm willing to give it another try, although it will take me a little while to get my head around it again. Is there any chance you could put one of the files somewhere I can retrieve it (share via Dropbox or Google Drive or ... ?) That would definitely be the most efficient way for me to dig in and figure out what's going on ...

**Comment by bbolker** [comment]
I can confirm that I see the breakage:

```r
> L <- load("day_model_full_activesteps_id_anim_woAlternate_NoSpring.RData")
> summary(glmm.TMB.random_d)
Error in if (ntot == ncol(X) || !include_dropped) { : 
  missing value where TRUE/FALSE needed
> x <- up2date(glmm.TMB.random_d)
Error in TMB::MakeADFun(data, parameters, map = map, random = random,  : 
  A map factor length must equal parameter length
```

will take a look at this when I get a chance.

**Comment by bbolker** [comment]
OK, try 

```
remotes::install_github("glmmTMB/glmmTMB/glmmTMB", ref = "up2date_mapped_disp")
```

That should (in theory) (1) give you a meaningful error message telling you to use `up2date()` if you try to call `vcov()` or `summary()` on the un-updated model, and (2) `up2date()` should work properly (although it takes 2 minutes to run on my system).  Let me know how it goes.

**Comment by BenediktGehr** [comment]
Thank you so much for this! I highly appreciate your time and effort for solving this issue! I tried quickly this morning and ran into issues with installing from git.hub due to some inconsistencies with dependencies. But I will try again later and definitely let you know once it worked.

Von: Ben Bolker ***@***.***>
Gesendet: 31 July 2024 01:34
An: glmmTMB/glmmTMB ***@***.***>
Cc: Benedikt Gehr ***@***.***>; Mention ***@***.***>
Betreff: Re: [glmmTMB/glmmTMB] Load old fit to newer version/tryCatch to point to up2date? (Issue #874)


OK, try

remotes::install_github("glmmTMB/glmmTMB/glmmTMB", ref = "up2date_mapped_disp")

That should (in theory) (1) give you a meaningful error message telling you to use up2date() if you try to call vcov() or summary() on the un-updated model, and (2) up2date() should work properly (although it takes 2 minutes to run on my system). Let me know how it goes.

**Comment by BenediktGehr** [comment]
My apologies for not responding earlier. I tried and it works perfectly! Thank you so much for your help, it is really appreciated!!

Best
Ben

Von: Ben Bolker ***@***.***>
Gesendet: 31 July 2024 01:34
An: glmmTMB/glmmTMB ***@***.***>
Cc: Benedikt Gehr ***@***.***>; Mention ***@***.***>
Betreff: Re: [glmmTMB/glmmTMB] Load old fit to newer version/tryCatch to point to up2date? (Issue #874)


OK, try

remotes::install_github("glmmTMB/glmmTMB/glmmTMB", ref = "up2date_mapped_disp")

That should (in theory) (1) give you a meaningful error message telling you to use up2date() if you try to call vcov() or summary() on the un-updated model, and (2) up2date() should work properly (although it takes 2 minutes to run on my system). Let me know how it goes.

**Comment by bbolker** [comment]
Just need to merge the [pull request](https://github.com/glmmTMB/glmmTMB/pull/1077).
