### ISSUE TITLE
Missing description? 

### ISSUE THREAD

**Issue by jpiaskowski** [glmmTMB/glmmTMB#903]
Hi, I may be missing something obvious, so my apologies in advance, but is there a "Description" file for this repo/R package? I was trying to install via `remotes::install_github(...)` and ran into the lack of such a file. Thank you.

**Comment by bbolker** [comment]
The head directory of the repo has a [README](https://github.com/glmmTMB/glmmTMB/blob/master/README.md); the package itself lives in the `glmmTMB` subdirectory; the [DESCRIPTION file](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/DESCRIPTION) lives in that subdirectory.  There is also  a [GitHub pages site](https://glmmtmb.github.io/glmmTMB/), which includes installation instructions (among other things, that you need `remotes::install_github("glmmTMB/glmmTMB/glmmTMB")`, because the repo owner, the repo itself, and the package directory are all called "glmmTMB" ...)
