### ISSUE TITLE
accounting/ correcting autocorrelation in negative binomial regression

### ISSUE THREAD

**Issue by esau0518** [glmmTMB/glmmTMB#917]
hi there!

I am evaluating an intervention that reduces seclusion in mental health care wards.  So, I will be using negative binomial regression to determine if there is a significant difference between intervention and comparison sites in reducing seclusion events. My outcome variable will be seclusion events (SEC) and the predictor will be being in an ward where the intervention has been implemented (INT). 

One of the assumptions of negative binomial regression is that there is independence of observation. However, there is a possibility that a person admitted to an intervention ward will be secluded several times over time. As a remedy, I will need to account for the autocorrelation of data. How can I implement this using R? Below is the code thus far for my negative binomial regression using MASS package.

summary(sec1 <- glm.nb(SEC ~ INT, data = full_data))

**Comment by mebrooks** [comment]
Please see[ Where to ask questions](https://github.com/glmmTMB/glmmTMB#where-to-ask-questions) and follow the advice there.
Also, your question isn't clear to me. If a person is secluded 5 times, does that make your response variable 5? Then you don't need to worry about the correlation among those 5 seclusions because they're a single observed response.
