### ISSUE TITLE
reinstalling issues on MacOS

### ISSUE THREAD

**Issue by nafreymueller** [glmmTMB/glmmTMB#927]
Hi, 

I am having issues installing a version of glmmTMB that is in sync with TMB, and this might be causing downstream issues for another package (sdmTMB) that relies on glmmTMB. 

When I first load glmmTMB into R, I get the following warning message:
```
Warning message:
In checkDepPackageVersion(dep_pkg = "TMB") :
  Package version inconsistency detected.
glmmTMB was built with TMB version 1.9.4
Current TMB version is 1.9.5
Please re-install glmmTMB from source or restore original ‘TMB’ package (see '?reinstalling' for more information)
```

Installing glmmTMB from the source and every option in reinstalling returns some sort of error message.

```
# both the following return the same type of error

install.packages("glmmTMB", type = "source")

remotes::install_github("glmmTMB/glmmTMB/glmmTMB")

* installing *source* package ‘glmmTMB’ ...
** package ‘glmmTMB’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
using C++ compiler: ‘clang version 8.0.0 (tags/RELEASE_800/final)’
using SDK: ‘MacOSX13.3.sdk’

# then I get a bunch of error messages that generally relate to:
error: use of undeclared identifier 'labs'; did you mean 'abs'?

# and this concludes with
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [glmmTMB.o] Error 1
ERROR: compilation failed for package ‘glmmTMB’
```

Reverting to the upstream packages just returns:
```
Warning in install.packages :
  unable to access index for repository https://mran.microsoft.com/snapshot/2023-07-10/src/contrib:
  cannot open URL 'https://mran.microsoft.com/snapshot/2023-07-10/src/contrib/PACKAGES'
Warning in install.packages :
  unable to access index for repository https://mran.microsoft.com/snapshot/2023-07-10/src/contrib:
  cannot open URL 'https://mran.microsoft.com/snapshot/2023-07-10/src/contrib/PACKAGES'
Warning in install.packages :
  package ‘TMB’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
Warning in install.packages :
  unable to access index for repository https://mran.microsoft.com/snapshot/2023-07-10/bin/macosx/big-sur-arm64/contrib/4.3:
  cannot open URL 'https://mran.microsoft.com/snapshot/2023-07-10/bin/macosx/big-sur-arm64/contrib/4.3/PACKAGES'
```
So I'm not sure if this is an issue with glmmTMB or base TMB at this point

These issues are currently running on the latest versions or R and MacOS on an M1 chip.
```
sessionInfo()
R version 4.3.1 (2023-06-16)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.4.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
```

Thanks for any help anyone can provide.

Cheers,
Nick

**Comment by bbolker** [comment]
I don't have a solution, but a few quick things:

* MRAN has been shut down.  You *should* be able to re-install the binaries from CRAN: if in doubt, you can download the binary (.tgz) files directly from the [CRAN page](https://cran.r-project.org/package=glmmTMB)
* the warning message may be ignorable: we have it there because binary incompatibilities in the Matrix > TMB > glmmTMB chain *sometimes* cause problems (I think any problems that do occur will be obvious rather than subtle/dangerous)
* I don't have direct access to a MacOS platform to check, but the [r-hub vignette](https://cran.r-project.org/web/packages/rhub/vignettes/rhub.html) lists clang 12.0.0; is your compiler out of date?  (Running `rhub::platforms()` locally doesn't list *any* MacOS options, so maybe these builders are offline?)
* We could try building on the [macOS builder provided by CRAN](https://mac.r-project.org/macbuilder/submit.html) (if you want to do this yourself, you have to edit the DESCRIPTION file to make yourself the maintainer ...)

**Comment by bbolker** [comment]
Are you sure that there's not a path/version problem somewhere so that you're using an older compiler than you think you are? The output you showed above includes

> using C++ compiler: ‘clang version 8.0.0 (tags/RELEASE_800/final)’

which is why I suggested that your compiler might be out of date. Maybe the compilation process is finding the wrong compiler ... ??

**Comment by nafreymueller** [comment]
Hmm. That could be the issue.

Inputting ```clang --version``` into Terminal results with the following:
```
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

When I try to install the package in base R instead of RStudio, I get the following:
```
remotes::install_github("glmmTMB/glmmTMB/glmmTMB")
Downloading GitHub repo glmmTMB/glmmTMB@HEAD
Error: Failed to install 'glmmTMB' from GitHub:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.

pkgbuild::check_build_tools(debug = TRUE)
Trying to compile a simple C file
Running /Library/Frameworks/R.framework/Resources/bin/R CMD SHLIB foo.c
Error: Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.

pkgbuild::check_build_tools(debug = TRUE)
Trying to compile a simple C file
Error: Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.

```

This gets outside my coding wheelhouse at this point. If it's just the case of making a simple change to R's Makeovers file, I can easily do that.

**Comment by bbolker** [comment]
It's outside of my wheelhouse too ("Makeovers file" → "Makevars file") ?  This seems like a question for `r-help@r-project.org` *or* the [RStudio IDE section of the Posit forum](https://community.rstudio.com/c/rstudio-ide/9). If I were you (since I don't use RStudio) I would check [the R-tools information for MacOS](https://mac.r-project.org/tools/). I would also check any existing `Makevars` or `.Rprofile` files (and try moving them out of the way to check whether they have problematic settings).

I will probably close this soon as it's not a (glmm)TMB-specific problem. If you can't resolve it, we might be able to update the repository [here](https://glmmtmb.github.io/glmmTMB/repos/index.html) with an up-to-date binary version ...

**Comment by nafreymueller** [comment]
Thanks for the input. The author of the downstream package mentioned it likely isn't a glmmTMB issue at this point (or potentially even a within-R issue). I'll give these options a go.

**Comment by bbolker** [comment]
I compiled a binary version of the package on the CRAN M1 macos builder. Does this work for you?

```
install.packages("glmmTMB",
                 repos = c("https://glmmTMB.github.io/glmmTMB/repos",
                           getOption("repos")["CRAN"]))
```

**Comment by nafreymueller** [comment]
Yes! Thank you! This works fine for me. I'm still having issues with the downstream package, but it's getting caught up[ on the same issue, so it's unlikely a glmmTMB issue.
