### ISSUE TITLE
Does glmmTMB handle integer64

### ISSUE THREAD

**Issue by andrebolerbarros** [glmmTMB/glmmTMB#948]
Hey everyone,

I was wondering if glmmTMB can handle integer64 values? I have some values that can only be saved in integer when saved in 64-bit.

Thanks!

**Comment by bbolker** [comment]
It doesn't, but I'm having a hard time seeing the use case (and would be curious). When would converting integer64 to floating point make a difference to the kind of problems that glmmTMB is designed for?

**Comment by andrebolerbarros** [comment]
To give you a short summary:

We are looking at counts of bacteria between treatments, in different time-points. Considering we have some zeros, we are using a zero-inflated negative binomial. Therefore, we want to have the values as integers.

For one of the experiments, one of the values is 5450450450, which comes as "NA" when `as.integer` is performed; therefore, we transformed it using the function `as.integer64`

**Comment by bbolker** [comment]
OK. Internally everything is done with floating point calculations (even in base R); furthermore, since 0 is exactly representable in floating point, there's no need to be careful about testing for exact equality. (This is true of every GLM-type modeling machine I know of; tests for integer responses are only done to try to detect user errors [applying a count-data model on non-count data].)

If it looks like the answer to your question is "yes", you can close this issue ...
