### ISSUE TITLE
Typo/ mistake in glmmtmb dokumentation regarding parameterization of nbinom1

### ISSUE THREAD

**Issue by sophiafrei** [glmmTMB/glmmTMB#951]
Hallo,
i am quite sure this has to be an mistake: in the dokumentation there is written regarding the nbinom1 parameterization: V=mu*(1+phi).
I think this has to be: V=mu*(1+1/phi). Like it is now it doesnt fit to the nbinom2 parameterization...
King regards,
Sophia Freimüller

**Comment by bbolker** [comment]
I'll take a look. The source code that computes the log-likelihood is [here](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/src/glmmTMB.cpp#L721-L728):

```
case truncated_nbinom1_family:
  // Was:
  //   s1 = mu(i);
  //   s2 = mu(i) * (Type(1)+phi(i));  // (1+phi) guarantees that var >= mu
 //   tmp_loglik = dnbinom2(yobs(i), s1, s2, true);
 s1 = log_inverse_linkfun(eta(i), link);          // log(mu)
 s2 = s1 + etad(i) ;                              // log(var - mu)
 tmp_loglik = dnbinom_robust(yobs(i), s1, s2, true);
```

This is a little harder to read because all the computation is done on the log scale. You also need to know that the [`dnbinom_robust` function](https://kaskr.github.io/adcomp/group__R__style__distribution.html#gaa23e3ede4669d941b0b54314ed42a75c) is parameterized by the `log(mu)` and `log(var-mu)` arguments. 

I'll have to come back and work through this carefully.

**Comment by bbolker** [comment]
Is there any clarification we can add to the documentation to avoid this confusion?

**Comment by sophiafrei** [comment]
At least for me it would be less confusing with different parameters. I am aware of the parameterizations with theta (or ny) and alpha (alpha = 1/theta) as in hilbe 2011. You could use theta for nbinom2 and alpha for nbinom1. As it is right now it implies an indirect relationship between phi_nbinom1 and phi_nbinom2 if i get it correct.

**Comment by bbolker** [comment]
I'm going to go ahead and close this: while it might be nice to sit down and review all the parameterizations, and make them consistent with each other as far as possible, we will always have inconsistency somewhere (either between the different parameterizations within `glmmTMB`, or between `glmmTMB` and common parameterizations in the literature. I've added a clarifying note to the documentation.
