### ISSUE TITLE
Family extensions: ordinal response using cumulative link models and other variants

### ISSUE THREAD

**Issue by DrJerryTAO** [glmmTMB/glmmTMB#982]
As an extension to binary regression, cumulative link models allow ordinal response using the same distribution families. There are also adjacent category, continuing ratio, and stopping ratio models that are closely related but use different probability mass function. Will @mebrooks and other developers consider extending the families to include those for an ordinal response? In these models, zero inflation shouldn't be an issue, and a constant `ziformula = ~0` should be reasonable. However, there will be a threshold-invariant-coefficient assumption to consider, which is commonly known as proportional odds, parallel line, or parallel regression assumption. Christensen (2022) relaxed this assumption and allowed threshold-variant coefficients called "nominal effects". I like the potential to model scale effects through `dispformula = ~ ...` and random effects. 

A useful reference: Christensen, R. H. B. (2022). Cumulative link models for ordinal regression with the R package ordinal. https://cran.r-project.org/web/packages/ordinal/vignettes/clm_article.pdf which allows only cumulative link models but not adjacent category, continuing ratio, and stopping ratio models. 
Yee, T. W. (2010). The VGAM package for categorical data analysis. Journal of Statistical Software, 32(1), Article 1. https://doi.org/10.18637/jss.v032.i10 which does not allow dispersion (i.e., scale) nor random effects.

**Comment by bbolker** [comment]
Hi @MrJerryTAO,
 
 The answer to this feature request is pretty much the same as that for [your other feature request](https://github.com/glmmTMB/glmmTMB/issues/981#issuecomment-1908260729) - "sounds fine, but we don't necessarily have any resources for that".

We should probably add a general FAQ for how we consider feature requests. Speaking just for myself (not *necessarily* on behalf of the other developers, feature requests are more likely to be honored if

* a clean pull request is provided 
* it's an **easy** extension of functionality that's already in the package
* it doesn't require additions to the package API (i.e., other arguments being specified/passed to the TMB code) &mdash; this is particularly paralyzing because API decisions should ideally be future-proof
* it's useful to lots of people
* it's useful to the developers and their friends/colleagues
* it's not already available in another R package

**Comment by bbolker** [comment]
I'm closing this as a duplicate (nearly) of #514
